[SUPPORT] LPS-156865 Create upgrade to remove view permissions for guest users from DDMFormInstance
liferay-forms/liferay-portal pull request #1788
Opened 2022-06-27 14:18 UTC by JavierMoral

Hi team,
This pr fixes [LPS-156865](https://issues.liferay.com/browse/LPS-156865).

For context please check [this comment](https://issues.liferay.com/browse/LPS-113264?focusedCommentId=2703246&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2703246). First I created a Groovy script to fix this but I was asked to transform it into an upgrade process [see here](https://issues.liferay.com/browse/LPS-113264?focusedCommentId=2708293&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2708293).
Thanks!

2022-06-27 14:19 UTC, JavierMoral commented
ci:test:relevant

2022-06-27 14:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4493/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4493/jenkins-report.html">here</a>.</b></p>

2022-06-28 09:33 UTC, JavierMoral commented
ci:test:relevant

2022-06-28 10:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1822/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1822/jenkins-report.html">here</a>.</b></p>

2022-06-28 12:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 169 out of 175 jobs passed in 1 hour 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/11724df470f8b261c94043e706e8a8f438a8e4c6">11724df470f8b261c94043e706e8a8f438a8e4c6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/11724df470f8b261c94043e706e8a8f438a8e4c6">11724df470f8b261c94043e706e8a8f438a8e4c6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3466">Acceptance Upstream DXP (master) #3466</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31462/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86172/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/82512/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62771/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/32640/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31561/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33324/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38041/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36939/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/35350/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89291/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/79791/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86739/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89290/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/84153/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36492/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/82489/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36489/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/79788/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86737/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89288/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37679/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62776/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86733/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31463/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29147/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/85016/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 169 out of 175 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1822/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/32742/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38036/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73757/"><strike>modules-integration-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/85020/"><strike>modules-integration-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86180/"><strike>modules-integration-mysql57-jdk8/0/11</strike></a></li></ul></li></ul></div><details><summary><strong>169 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/85017/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/84154/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36909/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31462/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29146/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86174/"> [...]

2022-06-28 12:47 UTC, carolmariaabb requested changes

2022-06-28 12:47 UTC, carolmariaabb commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v5_1_5/DDMFormInstanceUpgradeProcess.java
> +	}
Hi @JavierMoral,
I think we could simplify this code by doing something like:

```
@Override
protected void doUpgrade() throws Exception {
	try (PreparedStatement selectPreparedStatement =
			connection.prepareStatement(
				"select companyId, formInstanceId from DDMFormInstance");
		ResultSet resultSet = selectPreparedStatement.executeQuery()) {

		while (resultSet.next()) {
			long companyId = resultSet.getLong(1);
			long formInstanceId = resultSet.getLong(2);

			Role guestRole = _roleLocalService.getRole(
				companyId, RoleConstants.GUEST);

			ResourcePermission resourcePermission =
				_resourcePermissionLocalService.getResourcePermission(
					companyId, _CLASS_NAME_FORM_INSTANCE,
					ResourceConstants.SCOPE_INDIVIDUAL,
					String.valueOf(formInstanceId), guestRole.getRoleId());

			if (!resourcePermission.hasActionId(ActionKeys.VIEW)) {
				continue;
			}

			_resourcePermissionLocalService.removeResourcePermission(
				companyId, _CLASS_NAME_FORM_INSTANCE,
				ResourceConstants.SCOPE_INDIVIDUAL,
				String.valueOf(formInstanceId), guestRole.getRoleId(),
				ActionKeys.VIEW);
		}
	}
}

private static final String _CLASS_NAME_FORM_INSTANCE =
	"com.liferay.dynamic.data.mapping.model.DDMFormInstance";
```

2022-06-28 12:47 UTC, carolmariaabb commented
Hi @JavierMoral, thank you for working on this.

Although I understand the purpose of creating this upgrade step, I am not convinced that this is the best solution for the described issue. There may be cases where we shouldn't remove the permissions because the admin has set them manually, for example.

Could you please open a PTR ticket so we can involve the Product Team in this discussion?

Thanks!

2022-07-01 11:40 UTC, carolmariaabb commented
Hi @JavierMoral,

I'll close this PR for now and wait for the PTR ticket. I understand that it was suggested to create this upgrade process, but the current team would like to discuss a little more about how we can address this issue.

Thanks for your comprehension.

2022-07-01 11:40 UTC, carolmariaabb commented
ci:close

2022-07-01 11:41 UTC, closed without merging

2022-07-08 11:41 UTC, almonwork commented
Hi @carolmariaabb, @JavierMoral ,

Provided it was agreed in https://issues.liferay.com/browse/PTR-3187 that this approach should be valid, could we move this forward?

Regards

2022-07-08 11:43 UTC, carolmariaabb commented
Hi @JavierMoral, 

Can you please apply the changes suggested [here](https://github.com/liferay-forms/liferay-portal/pull/1788#discussion_r908432237) and resend this PR?

Thanks