LPS-131246
liferay-forms/liferay-portal pull request #241
Opened 2021-05-14 18:20 UTC by wesleyroberts

2021-05-14 18:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-14 18:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3581/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3581/jenkins-report.html">here</a>.</b></p>

2021-05-14 18:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28d242fcdd7e93ad36471133659b1905b7b855c5">28d242fcdd7e93ad36471133659b1905b7b855c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/wesleyroberts/liferay-portal/tree/LPS-131246">LPS-131246</a><br/>Branch GIT ID: <a href="https://github.com/wesleyroberts/liferay-portal/commit/782b42c204f6358a79da928e7f5823072a0b0fb0">782b42c204f6358a79da928e7f5823072a0b0fb0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3581/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3581/jenkins-report.html">here</a>.</h5></details></html>

2021-05-14 18:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3581/">test-portal-source-format#3581</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3581/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/241">liferay-forms#241</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532745572">[master] ci:test:sf - wesleyroberts &gt; liferay-forms - PR#241 - 2021-05-14[11:21:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/649/">publish-testray-report#649</a><br/></div></div>

2021-05-14 18:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/8023/">test-portal-acceptance-pullrequest(master)#8023</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8023/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/241">liferay-forms#241</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532745581">[master] ci:test:relevant - wesleyroberts &gt; liferay-forms - PR#241 - 2021-05-14[11:21:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/743/">publish-testray-report#743</a><br/></div></div>

2021-05-14 20:34 UTC, brittneyq commented
ci:test:forms-functional

2021-05-14 20:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>forms-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/139/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/139/jenkins-report.html">here</a>.</b></p>

2021-05-14 20:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:forms-functional - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28d242fcdd7e93ad36471133659b1905b7b855c5">28d242fcdd7e93ad36471133659b1905b7b855c5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b2df07e393f9f46c83b605e0a50e6f03c699cdf4">b2df07e393f9f46c83b605e0a50e6f03c699cdf4</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1864">Acceptance Upstream DXP (master) #1864</a></p><details><summary><strong>ci:test:forms-functional - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/139/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/139/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/139/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The CI test suite 'forms-functional' is not a valid test suite.

List of available CI test suites:
* acceptance
* acceptance-functional
* acceptance-upstream
* accounts
* analytics-cloud
* app-builder
* auto-tagging
* backend
* backend-hypersonic
* blade
* blogs
* bulk-editing
* bundle
* calendar
* click-to-chat
* clustering
* commerce
* commerce-es7-remote
* commerce-functional
* content-page-review
* data-engine
* depot
* dl-store
* documents
* drools
* dummy
* echo
* echo-acceptance
* echo-upgrade
* environments
* export-import
* forms
* frontend
* gauntlet
* gauntlet-bucket
* gradle-plugins
* headless
* headless-acceptance
* jdk11
* jsf
* kaleo-forms
* knowledge-base
* ldap
* license
* license-cluster
* liferay-online
* lima
* lpkg
* message-boards
* oauth2
* onedrive
* online-editing
* poshi
* poshi-gauntlet
* project-templates
* publications
* publications-environments
* questions-acceptance
* redirect
* relevant
* reports
* roles
* saml
* search
* search-remote
* search-remote-minimum
* security
* seo
* sf
* sharepoint
* sharing
* site-template
* smoke
* stable
* staging
* sybase
* system
* tango
* tango-acceptance
* tango-analytics-cloud
* tck
* translations
* upgrade
* upgrade-client
* upstream-functional
* users
* usm
* usm-upgrade
* vulcan-acceptance
* wiki
* workflow
* workflow-es7-remote
* workflow-metrics

</p><p>Comment 'ci:help' for details.</p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-05-14 20:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/139/">test-portal-acceptance-pullrequest(master)#139</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/139/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>forms-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/241">liferay-forms#241</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532782244">[master] ci:test:forms-functional - wesleyroberts &gt; liferay-forms - PR#241 - 2021-05-14[13:35:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/306/">publish-testray-report#306</a><br/></div></div>

2021-05-14 23:27 UTC, brittneyq commented
@natocesarrego @diogocordeiro 
This is ready for review. Could not run ci:test:forms-functional since it doesn't seem to be included in the test suite.

2021-05-17 19:02 UTC, diogocordeiro requested changes

2021-05-18 16:49 UTC, wesleyroberts commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/CKEditor.path
> +<tr>
Change made

2021-05-18 19:05 UTC, brittneyq commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/CKEditor.path
> +<tr>
Hi Wesley, could you please discard your changes to CKEditor.path since you moved the path to the FormFields file?

2021-05-20 19:46 UTC, brittneyq commented
Hi @wesleyroberts, please fix conflicting files and also remove the CkEditor file from your commit since the path is in FormFields now.

2021-05-20 21:26 UTC, wesleyroberts commented
changes made

2021-05-20 21:41 UTC, brittneyq commented
Hi @wesleyroberts , please remove any changes to CkEditor.path and remove that file from your commit as well. Thanks

2021-05-21 13:17 UTC, wesleyroberts commented
I rebase the branch and resolved pending conflicts, and also removed the TOOLBAR_ANY_ITEM_BUTTON path from the CKEditor.path file.

2021-05-21 13:21 UTC, wesleyroberts commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/CKEditor.path
> +<tr>
I rebase the branch and resolved pending conflicts, and also removed the TOOLBAR_ANY_ITEM_BUTTON path from the CKEditor.path file.

2021-05-21 14:26 UTC, diogocordeiro commented
ci:forward

2021-05-21 14:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-21 14:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc5ccd2a3e82780cc87de95c93973ee585d632ab">cc5ccd2a3e82780cc87de95c93973ee585d632ab</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/wesleyroberts/liferay-portal/tree/LPS-131246">LPS-131246</a><br/>Branch GIT ID: <a href="https://github.com/wesleyroberts/liferay-portal/commit/a9dd4cfca287a366c4d776468ee3622233c75213">a9dd4cfca287a366c4d776468ee3622233c75213</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5692/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5692/jenkins-report.html">here</a>.</h5></details></html>

2021-05-21 14:30 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/test-portal-source-format/5692//consoleFull)

2021-05-21 14:30 UTC, closed without merging

2021-05-21 14:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5692/">test-portal-source-format#5692</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5692/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/241">liferay-forms#241</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1534411897">[master] ci:test:sf - wesleyroberts &gt; liferay-forms - PR#241 - 2021-05-21[07:26:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/1011/">publish-testray-report#1011</a><br/></div></div>

2021-05-21 17:00 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8362//consoleFull)

2021-05-21 17:00 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2021-05-21 17:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8362/">test-portal-acceptance-pullrequest(master)#8362</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8362/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/241">liferay-forms#241</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1534435691">[master] ci:test:relevant - wesleyroberts &gt; liferay-forms - PR#241 - 2021-05-21[09:58:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/1013/">publish-testray-report#1013</a><br/></div></div>