LPS-204047 Fix modal form export entries layout
liferay-forms/liferay-portal pull request #2420
Opened 2023-12-18 13:42 UTC by titokenzo

2023-12-18 13:45 UTC, titokenzo commented
ci:test:sf

2023-12-18 17:07 UTC, carolmariaabb commented
ci:test:sf

2023-12-19 16:47 UTC, cgmonte requested changes
Hi @titokenzo, thanks for sending this fix! Its was a very weird behavior and I have seen that in other places of the portal. It makes total sense to have the form inside the body and the button inside the footer, connected to the form by the `form` attribute. Nice fix. I made some minor change requests, please check them and let me know if anything does no make sense.

2023-12-19 16:47 UTC, cgmonte commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/js/components/export-form/ExportFormModal.tsx
> + * ANY WARRANTY; without even te implied warranty of MERCHANTABILITY or FITNESS
Even though you change the license text on next commit, this shouldn't be here, as if for any reason next commit gets dropped, this doesn't stay in master. Please, remove this change from this commit.

2023-12-19 16:47 UTC, cgmonte commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/js/components/export-form/ExportFormModal.tsx
> +					id="exportFormEntriesFormId"
I am no sure about this string. I have never seen a ID string ending in "Id", this is already implicit. You don't add "Id" suffixes to ID strings. On the bright side, down at the `<button>` `form` attribute, having "Id" kind of makes things clearer for beginners programmers who may not know that this is referencing a form ID. I would say: remove the suffix, make it only "exportFormEntriesForm". What do you think?

2023-12-19 16:47 UTC, cgmonte commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/js/components/export-form/ExportFormModal.tsx
> +							form="exportFormEntriesFormId"
Read above comment. One should know that this is and Id.

2023-12-19 16:47 UTC, cgmonte commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/js/components/export-form/ExportFormModal.tsx
> + * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
This is not the latest. Should it be? Se a 2023 license here:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ModelBuilder/index.tsx#L1-L4

2023-12-20 14:25 UTC, cgmonte approved these changes
LGTM!

2023-12-20 14:26 UTC, cgmonte commented
ci:forward

2023-12-20 14:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-12-20 14:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3075/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3075/jenkins-report.html">here</a>.</b></p>

2023-12-20 14:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b808cb100001223008944254d5da1364de64c622">b808cb100001223008944254d5da1364de64c622</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/titokenzo/liferay-portal/tree/LPS-204047-dxp-master">LPS-204047-dxp-master</a><br/>Branch GIT ID: <a href="https://github.com/titokenzo/liferay-portal/commit/2e2e364a5b02d166d56f30145f9f2ea0638254f3">2e2e364a5b02d166d56f30145f9f2ea0638254f3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3075/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3075/jenkins-report.html">here</a>.</h5></details></html>

2023-12-20 14:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3075/">test-portal-source-format#3075</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3075/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/2420">liferay-forms#2420</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2477194864">[master] ci:test:sf - titokenzo &gt; liferay-forms - PR#2420 - 2023-12-20[06:26:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/22348/">publish-testray-report#22348</a><br/></div></div>

2023-12-20 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5526/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5526/jenkins-report.html">here</a>.</b></p>

2023-12-20 16:30 UTC, carolmariaabb commented
ci:forward:force

2023-12-20 16:30 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-12-20 16:30 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2023-12-20 16:31 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-36.liferay.com/job/forward-pullrequest/476//consoleFull)

2023-12-20 16:31 UTC, closed without merging

2023-12-20 16:31 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/145508
[Console](https://test-1-36.liferay.com/job/forward-pullrequest/476//consoleFull)

2023-12-20 16:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5526/">test-portal-acceptance-pullrequest(master)#5526</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5526/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/2420">liferay-forms#2420</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2477291945">[master] ci:test:relevant - titokenzo &gt; liferay-forms - PR#2420 - 2023-12-20[06:38:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/22349/">publish-testray-report#22349</a><br/></div></div>