LPS-131224
liferay-forms/liferay-portal pull request #243
Opened 2021-05-14 19:05 UTC by LucasAcacio

2021-05-14 19:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-14 19:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6528/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6528/jenkins-report.html">here</a>.</b></p>

2021-05-14 19:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28d242fcdd7e93ad36471133659b1905b7b855c5">28d242fcdd7e93ad36471133659b1905b7b855c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/LPS-131224">LPS-131224</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/95b6a5632539a7e3637cc986a780d45b0abca979">95b6a5632539a7e3637cc986a780d45b0abca979</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6528/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6528/jenkins-report.html">here</a>.</h5></details></html>

2021-05-14 19:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6528/">test-portal-source-format#6528</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6528/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/243">liferay-forms#243</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532747122">[master] ci:test:sf - LucasAcacio &gt; liferay-forms - PR#243 - 2021-05-14[12:05:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/673/">publish-testray-report#673</a><br/></div></div>

2021-05-14 19:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/8234/">test-portal-acceptance-pullrequest(master)#8234</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8234/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/243">liferay-forms#243</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532747131">[master] ci:test:relevant - LucasAcacio &gt; liferay-forms - PR#243 - 2021-05-14[12:05:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/1198/">publish-testray-report#1198</a><br/></div></div>

2021-05-15 00:08 UTC, brittneyq commented
@natocesarrego @diogocordeiro this should be ready for review!

2021-05-17 18:11 UTC, diogocordeiro requested changes

2021-05-17 18:11 UTC, diogocordeiro commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsParagraphField.testcase
>  	}
Hi @LucasAcacio, 

I am not sure but I think this last step on the test is missing --> 
10. Assert the new Paragraph field's field reference is different from the field reference of the original Paragraph field. 

Can you verify this, please? 

Thanks!

2021-05-17 22:45 UTC, brittneyq commented
Hi @LucasAcacio, there seems to be conflicting files with this PR for `portal-web/test/functional/com/liferay/portalweb/paths/portlet/forms/FormFields.path`
 would you mind making the appropriate changes?

2021-05-20 13:12 UTC, diogocordeiro commented
ci:forward

2021-05-20 13:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-20 13:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3617/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3617/jenkins-report.html">here</a>.</b></p>

2021-05-20 13:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de56c0014c64d9fac09982075739384a05abeff2">de56c0014c64d9fac09982075739384a05abeff2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/LPS-131224">LPS-131224</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/807f7d2b9cba30c825a47d2439747e60b66634f5">807f7d2b9cba30c825a47d2439747e60b66634f5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3617/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3617/jenkins-report.html">here</a>.</h5></details></html>

2021-05-20 13:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102091
[Console](https://test-1-12.liferay.com/job/test-portal-source-format/3617//consoleFull)

2021-05-20 13:17 UTC, closed without merging

2021-05-20 13:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3617/">test-portal-source-format#3617</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3617/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/243">liferay-forms#243</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1534059497">[master] ci:test:sf - LucasAcacio &gt; liferay-forms - PR#243 - 2021-05-20[06:13:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/760/">publish-testray-report#760</a><br/></div></div>

2021-05-20 14:10 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/102091

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4744//consoleFull)