LPS-131233
liferay-forms/liferay-portal pull request #246
Opened 2021-05-14 20:57 UTC by LucasAcacio

2021-05-14 20:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-14 20:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4726/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4726/jenkins-report.html">here</a>.</b></p>

2021-05-14 21:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/28d242fcdd7e93ad36471133659b1905b7b855c5">28d242fcdd7e93ad36471133659b1905b7b855c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/LPS-131233">LPS-131233</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/1c634620f95b44e94841f20453efb52b25652825">1c634620f95b44e94841f20453efb52b25652825</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4726/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4726/jenkins-report.html">here</a>.</h5></details></html>

2021-05-14 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7393/">test-portal-acceptance-pullrequest(master)#7393</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7393/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/246">liferay-forms#246</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532793868">[master] ci:test:relevant - LucasAcacio &gt; liferay-forms - PR#246 - 2021-05-14[13:58:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/818/">publish-testray-report#818</a><br/></div></div>

2021-05-14 21:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4726/">test-portal-source-format#4726</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4726/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/246">liferay-forms#246</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532793878">[master] ci:test:sf - LucasAcacio &gt; liferay-forms - PR#246 - 2021-05-14[13:58:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/819/">publish-testray-report#819</a><br/></div></div>

2021-05-17 18:45 UTC, diogocordeiro requested changes

2021-05-17 18:45 UTC, diogocordeiro commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/CKEditor.path
> +<tr>
Hi @LucasAcacio ,

Although the CKEditor.path file exists this test is in the context of forms, we prefer that Paths be kept in our own files. Could you please remove this path from this file and add it on the FormFields.path file instead.

Thanks!

2021-05-25 23:40 UTC, emanuelfisilva commented
Great work @LucasAcacio . 
I've only removed the path you created during rebase since it's already on Master.
Please follow: https://github.com/liferay-forms/liferay-portal/pull/354

2021-05-25 23:40 UTC, closed without merging