LPS-131234
liferay-forms/liferay-portal pull request #247
Opened 2021-05-14 20:59 UTC by leticiachiu

2021-05-14 21:17 UTC, CalumR23 commented
ci:test:relevant

2021-05-14 21:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8323/">test-portal-acceptance-pullrequest(master)#8323</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8323/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/247">liferay-forms#247</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532794220">[master] ci:test:relevant - leticiachiu &gt; liferay-forms - PR#247 - 2021-05-14[14:17:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/715/">publish-testray-report#715</a><br/></div></div>

2021-05-15 00:03 UTC, brittneyq commented
ci:test:sf

2021-05-15 00:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">here</a>.</b></p>

2021-05-15 00:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6d64d6aba3f4d1080233fbffb7bb26491d996e86">6d64d6aba3f4d1080233fbffb7bb26491d996e86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LPS-131234">LPS-131234</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/63ed495e48479e1faa2d32b9a5783a798038b3ce">63ed495e48479e1faa2d32b9a5783a798038b3ce</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">here</a>.</h5></details></html>

2021-05-15 00:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5797/">test-portal-source-format#5797</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5797/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/247">liferay-forms#247</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532808897">[master] ci:test:sf - leticiachiu &gt; liferay-forms - PR#247 - 2021-05-14[17:03:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/748/">publish-testray-report#748</a><br/></div></div>

2021-05-15 00:11 UTC, brittneyq commented
@natocesarrego , @diogocordeiro these should be ready for review!

2021-05-17 17:56 UTC, diogocordeiro commented
ci:test:forms-functional

2021-05-17 18:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>forms-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/8537/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8537/jenkins-report.html">here</a>.</b></p>

2021-05-17 18:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:forms-functional - 0 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/20d43f6c27421c80698b993d79f6b83eef6d6c1d">20d43f6c27421c80698b993d79f6b83eef6d6c1d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5017f0d112594164c8de23386975cc867d4c1b2">b5017f0d112594164c8de23386975cc867d4c1b2</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1868">Acceptance Upstream DXP (master) #1868</a></p><details><summary><strong>ci:test:forms-functional - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/8537/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8537/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/8537/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The CI test suite 'forms-functional' is not a valid test suite.

List of available CI test suites:
* acceptance
* acceptance-functional
* acceptance-upstream
* accounts
* analytics-cloud
* app-builder
* auto-tagging
* backend
* backend-hypersonic
* blade
* blogs
* bulk-editing
* bundle
* calendar
* click-to-chat
* clustering
* commerce
* commerce-es7-remote
* commerce-functional
* content-page-review
* data-engine
* depot
* dl-store
* documents
* drools
* dummy
* echo
* echo-acceptance
* echo-upgrade
* environments
* export-import
* forms
* frontend
* gauntlet
* gauntlet-bucket
* gradle-plugins
* headless
* headless-acceptance
* jdk11
* jsf
* kaleo-forms
* knowledge-base
* ldap
* license
* license-cluster
* liferay-online
* lima
* lpkg
* message-boards
* oauth2
* onedrive
* online-editing
* poshi
* poshi-gauntlet
* project-templates
* publications
* publications-environments
* questions-acceptance
* redirect
* relevant
* reports
* roles
* saml
* search
* search-remote
* search-remote-minimum
* security
* seo
* sf
* sharepoint
* sharing
* site-template
* smoke
* stable
* staging
* sybase
* system
* tango
* tango-acceptance
* tango-analytics-cloud
* tck
* translations
* upgrade
* upgrade-client
* upstream-functional
* users
* usm
* usm-upgrade
* vulcan-acceptance
* wiki
* workflow
* workflow-es7-remote
* workflow-metrics

</p><p>Comment 'ci:help' for details.</p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-05-17 18:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/8537/">test-portal-acceptance-pullrequest(master)#8537</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8537/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>forms-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/247">liferay-forms#247</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1533168549">[master] ci:test:forms-functional - leticiachiu &gt; liferay-forms - PR#247 - 2021-05-17[10:56:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/964/">publish-testray-report#964</a><br/></div></div>

2021-05-17 18:44 UTC, diogocordeiro requested changes

2021-05-17 18:44 UTC, diogocordeiro commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/CKEditor.path
> +<tr>
Hi @leticiachiu ,

Although the CKEditor.path file exists this test is in the context of forms, we prefer that Paths be kept in our own files. Could you please remove this path from this file and add it on the FormFields.path file instead.

Thanks!

2021-05-18 12:56 UTC, diogocordeiro commented
ci:forward

2021-05-18 12:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-18 12:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3597/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3597/jenkins-report.html">here</a>.</b></p>

2021-05-18 13:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2525abbf42901829bc1f03a70f5fd85f7c4d0bd8">2525abbf42901829bc1f03a70f5fd85f7c4d0bd8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LPS-131234">LPS-131234</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/3c72a9c7c542f2f21e0e42e3760f1e0ee665a5c7">3c72a9c7c542f2f21e0e42e3760f1e0ee665a5c7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3597/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3597/jenkins-report.html">here</a>.</h5></details></html>

2021-05-18 13:01 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-12.liferay.com/job/test-portal-source-format/3597//consoleFull)

2021-05-18 13:01 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101938
[Console](https://test-1-12.liferay.com/job/test-portal-source-format/3597//consoleFull)

2021-05-18 13:01 UTC, closed without merging

2021-05-18 13:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4711/">test-portal-acceptance-pullrequest(master)#4711</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4711/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/247">liferay-forms#247</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1533371074">[master] ci:test:relevant - leticiachiu &gt; liferay-forms - PR#247 - 2021-05-18[05:57:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/690/">publish-testray-report#690</a><br/></div></div>

2021-05-18 13:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3597/">test-portal-source-format#3597</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3597/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/247">liferay-forms#247</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1533371083">[master] ci:test:sf - leticiachiu &gt; liferay-forms - PR#247 - 2021-05-18[05:57:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/691/">publish-testray-report#691</a><br/></div></div>