LPD-17380 Use the editing language to get the success message according to the set language
liferay-forms/liferay-portal pull request #2470
Opened 2024-02-08 15:58 UTC by vngoliveira

[LPP-52619](https://liferay.atlassian.net/browse/LPP-52619)
[LPD-17380](https://liferay.atlassian.net/browse/LPD-17380)
Hi team!
When you create a form, add it to a new language, put a success message different for each language, and save or publish, the message for the other language is lost, so the default message (in English) is rendering.
I am using the editing language instead of the `Liferay.ThemeDisplay.getLanguageId()` to solve this issue.
Thank you for your attention and review. :blush:

2024-02-08 15:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-02-08 16:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7516/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7516/jenkins-report.html">here</a>.</b></p>

2024-02-08 16:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/53401963f02f593bbf555b4b321fdaeb59e03a53">53401963f02f593bbf555b4b321fdaeb59e03a53</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-17380">LPD-17380</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/ac0c37c09fee29247f7509b0bb7f28e597ba9e36">ac0c37c09fee29247f7509b0bb7f28e597ba9e36</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7516/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7516/jenkins-report.html">here</a>.</h5></details></html>

2024-02-08 16:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7516/">test-portal-source-format#7516</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7516/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/2470">liferay-forms#2470</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2536476115">[master] ci:test:sf - vngoliveira &gt; liferay-forms - PR#2470 - 2024-02-08[07:59:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2536476115<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/29531/">publish-testray-report#29531</a><br/></div></div>

2024-02-09 10:59 UTC, carolmariaabb requested changes

2024-02-09 10:59 UTC, carolmariaabb commented on modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/custom/form/renderer/SuccessVariant.es.js
>  					successPageSettings.title[defaultLanguageId])) ||
@vngoliveira your change is reverting the fix made for https://liferay.atlassian.net/browse/LPD-12649.

1. Change the language in the url to Spanish adding the “/es/” after the domain: http://localhost:8080/es/
2. Add a new Form
3. With your changes, the success message is now empty

![image](https://github.com/liferay-forms/liferay-portal/assets/34186632/0ce38fa9-9171-4a90-a4fb-2cb0a6e64e09)

Could you please check?

2024-02-09 11:27 UTC, vngoliveira commented
ci:test:sf

2024-02-09 11:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7673/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7673/jenkins-report.html">here</a>.</b></p>

2024-02-09 11:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/94a2c1a6ba5857ea26246856ae361ca6d5e42bce">94a2c1a6ba5857ea26246856ae361ca6d5e42bce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-17380">LPD-17380</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/a19342ea174e853028e145c89c63ba73a7a36640">a19342ea174e853028e145c89c63ba73a7a36640</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7673/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7673/jenkins-report.html">here</a>.</h5></details></html>

2024-02-09 11:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7673/">test-portal-source-format#7673</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7673/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/2470">liferay-forms#2470</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2536900372">[master] ci:test:sf - vngoliveira &gt; liferay-forms - PR#2470 - 2024-02-09[03:28:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2536900372<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/5013/">publish-testray-report#5013</a><br/></div></div>

2024-02-09 12:14 UTC, carolmariaabb commented
@vngoliveira please see https://github.com/liferay-forms/liferay-portal/pull/2471/

2024-02-09 12:14 UTC, closed without merging