LPS-130999
liferay-forms/liferay-portal pull request #268
Opened 2021-05-18 20:41 UTC by leilanyaragao

2021-05-18 22:47 UTC, brittneyq commented
Hi @leilanyaragao, since you didn't make any changes within the Button.path file, can you please remove that from your commit? Thank you!

2021-05-19 23:26 UTC, brittneyq commented
ci:test:sf

2021-05-19 23:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/5683/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/5683/jenkins-report.html">here</a>.</b></p>

2021-05-19 23:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/12ac4838bd1d6a999f3ad375e292218ca62dfce8">12ac4838bd1d6a999f3ad375e292218ca62dfce8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/LPS-130999">LPS-130999</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/4f32dcf79d26d77f9a24e0d115489149a263841a">4f32dcf79d26d77f9a24e0d115489149a263841a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5683/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5683/jenkins-report.html">here</a>.</h5></details></html>

2021-05-19 23:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5683/">test-portal-source-format#5683</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5683/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/268">liferay-forms#268</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1533946983">[master] ci:test:sf - leilanyaragao &gt; liferay-forms - PR#268 - 2021-05-19[16:26:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/989/">publish-testray-report#989</a><br/></div></div>

2021-05-20 21:04 UTC, diogocordeiro requested changes

2021-05-20 21:04 UTC, diogocordeiro commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/forms/FormFields.path
> +<!--PAGE-->
Hi @leilanyaragao , I think that all these paths are not related to a Form Field. I believe that this path is more related to a Form feature, so please could you remove it from this file and change it to the Form.path file, please?

2021-05-20 21:04 UTC, diogocordeiro commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> -		// TODO LPS-130999 PagesCanBeReordered pending implementation
After change the path remember to edit all places that uses this path

2021-05-26 16:15 UTC, brittneyq commented
ci:test:sf

2021-05-26 16:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/559/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/559/jenkins-report.html">here</a>.</b></p>

2021-05-26 16:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/26c6bc1b470b21c0ea00632554536f3a9ad8e17b">26c6bc1b470b21c0ea00632554536f3a9ad8e17b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/LPS-130999">LPS-130999</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/8a93c37b26037e6290342ee3fc011322727095c6">8a93c37b26037e6290342ee3fc011322727095c6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/559/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/559/jenkins-report.html">here</a>.</h5></details></html>

2021-05-26 16:20 UTC, brittneyq commented
ci:forward

2021-05-26 16:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-26 16:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/559/">test-portal-source-format#559</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/559/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/268">liferay-forms#268</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535628351">[master] ci:test:sf - leilanyaragao &gt; liferay-forms - PR#268 - 2021-05-26[09:16:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/1069/">publish-testray-report#1069</a><br/></div></div>

2021-05-26 16:21 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-2.liferay.com/job/forward-pullrequest/89//consoleFull)

2021-05-26 16:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102391
[Console](https://test-1-2.liferay.com/job/forward-pullrequest/89//consoleFull)

2021-05-26 16:22 UTC, closed without merging