LPS-130510
liferay-forms/liferay-portal pull request #274
Opened 2021-05-19 18:37 UTC by lima-rafa

2021-05-19 19:18 UTC, brittneyq commented
Hi @lima-rafa, it looks like you pushed two test cases, could you change it so only the test associated with the ticket is committed?

2021-05-20 21:08 UTC, brittneyq commented
ci:test:sf

2021-05-20 21:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5826/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5826/jenkins-report.html">here</a>.</b></p>

2021-05-20 21:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f620c75a2a63893f3d86f675cd35bc75ef980f2b">f620c75a2a63893f3d86f675cd35bc75ef980f2b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-130510">LPS-130510</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/f558e52db334c5f5abb300e1760a229b2c33fda1">f558e52db334c5f5abb300e1760a229b2c33fda1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5826/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5826/jenkins-report.html">here</a>.</h5></details></html>

2021-05-20 21:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5826/">test-portal-source-format#5826</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5826/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/274">liferay-forms#274</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1534159819">[master] ci:test:sf - lima-rafa &gt; liferay-forms - PR#274 - 2021-05-20[14:08:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/860/">publish-testray-report#860</a><br/></div></div>

2021-05-21 15:05 UTC, brunofariasdeo requested changes

2021-05-21 15:05 UTC, brunofariasdeo commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +			value1 = "Element Set Description");
We also have a macro that asserts the form description, which is `Form.viewFormDescription`.
In this case, you would use something similar to `Form.viewFormDescription(formDescription = "Form Description");`

2021-05-21 15:05 UTC, brunofariasdeo commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase
> +			locator1 = "FormViewBuilder#FIELD_LABEL");
There is a macro which you can use in order to check if the field label is already rendered, and it is the `FormFields.viewTextLabel`. 
You can use it by passing the field label as a parameter, something like `FormFields.viewTextLabel(fieldLabel = "Text")`.

2021-05-27 12:52 UTC, brunofariasdeo approved these changes

2021-05-27 12:52 UTC, brunofariasdeo commented
Very good, great job, @lima-rafa :)

2021-05-27 12:52 UTC, brunofariasdeo commented
ci:test:sf

2021-05-27 12:52 UTC, brunofariasdeo commented
ci:test:relevant

2021-05-27 12:52 UTC, brunofariasdeo commented
ci:forward

2021-05-27 12:52 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-27 12:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6587/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6587/jenkins-report.html">here</a>.</b></p>

2021-05-27 12:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ce21b9fe7d85e5144ea516e88afe948498158094">ce21b9fe7d85e5144ea516e88afe948498158094</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-130510">LPS-130510</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/70a0cc38f79c5f3cf0345abd74d3a5ba8264c087">70a0cc38f79c5f3cf0345abd74d3a5ba8264c087</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6587/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6587/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase expected:&lt;...ding implementation
     [java] [
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be deleted"
     [java] 	@priority = "5"
     [java] 	test CanBeDeleted \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		AssertElementPresent(
     [java] 			key_formName = "Form 1",
     [java] 			locator1 = "FormsAdmin#FORMS_TABLE_NAME");
     [java] 
     [java] 		FormsAdmin.deleteForm(formName = "Form 1");
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be duplicated"
     [java] 	@priority = "5"
     [java] 	test CanBeDuplicated \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.editDescription(formDescription = "Form Description");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		FormsAdminNavigator.gotoBack();
     [java] 
     [java] 		Form.duplicate(formName = "Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Copy of Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Form 1");
     [java] 
     [java] 		FormsAdminNavigator.gotoEditFormByName(formName = "Copy of Form 1");
     [java] 
     [java] 		Form.viewFormName(formName = "Copy of Form 1");
     [java] </code></pre></details></html>

2021-05-27 13:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6587/">test-portal-source-format#6587</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6587/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/274">liferay-forms#274</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535911217">[master] ci:test:sf - lima-rafa &gt; liferay-forms - PR#274 - 2021-05-27[05:54:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/856/">publish-testray-report#856</a><br/></div></div>

2021-05-27 13:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ce21b9fe7d85e5144ea516e88afe948498158094">ce21b9fe7d85e5144ea516e88afe948498158094</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-130510">LPS-130510</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/70a0cc38f79c5f3cf0345abd74d3a5ba8264c087">70a0cc38f79c5f3cf0345abd74d3a5ba8264c087</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5560/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5560/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase expected:&lt;...ding implementation
     [java] [
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be deleted"
     [java] 	@priority = "5"
     [java] 	test CanBeDeleted \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		AssertElementPresent(
     [java] 			key_formName = "Form 1",
     [java] 			locator1 = "FormsAdmin#FORMS_TABLE_NAME");
     [java] 
     [java] 		FormsAdmin.deleteForm(formName = "Form 1");
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be duplicated"
     [java] 	@priority = "5"
     [java] 	test CanBeDuplicated \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.editDescription(formDescription = "Form Description");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		FormsAdminNavigator.gotoBack();
     [java] 
     [java] 		Form.duplicate(formName = "Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Copy of Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Form 1");
     [java] 
     [java] 		FormsAdminNavigator.gotoEditFormByName(formName = "Copy of Form 1");
     [java] 
     [java] 		Form.viewFormName(formName = "Copy of Form 1");
     [java] </code></pre></details></html>

2021-05-27 14:03 UTC, brunofariasdeo commented
ci:test:sf

2021-05-27 14:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/575/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/575/jenkins-report.html">here</a>.</b></p>

2021-05-27 14:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ce21b9fe7d85e5144ea516e88afe948498158094">ce21b9fe7d85e5144ea516e88afe948498158094</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-130510">LPS-130510</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/70a0cc38f79c5f3cf0345abd74d3a5ba8264c087">70a0cc38f79c5f3cf0345abd74d3a5ba8264c087</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/575/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/575/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase expected:&lt;...ding implementation
     [java] [
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be deleted"
     [java] 	@priority = "5"
     [java] 	test CanBeDeleted \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		AssertElementPresent(
     [java] 			key_formName = "Form 1",
     [java] 			locator1 = "FormsAdmin#FORMS_TABLE_NAME");
     [java] 
     [java] 		FormsAdmin.deleteForm(formName = "Form 1");
     [java] 	\}
     [java] 
     [java] 	@description = "Verify that a Form can be duplicated"
     [java] 	@priority = "5"
     [java] 	test CanBeDuplicated \{
     [java] 		property forms.functional = "true";
     [java] 		property portal.acceptance = "false";
     [java] 
     [java] 		ProductMenu.gotoPortlet(
     [java] 			category = "Content &amp;amp; Data",
     [java] 			portlet = "Forms");
     [java] 
     [java] 		FormsAdminNavigator.gotoAddForm();
     [java] 
     [java] 		Form.editName(formName = "Form 1");
     [java] 
     [java] 		Form.editDescription(formDescription = "Form Description");
     [java] 
     [java] 		Form.addTextField(fieldPositionNumber = "0");
     [java] 
     [java] 		Form.save();
     [java] 
     [java] 		FormsAdminNavigator.gotoBack();
     [java] 
     [java] 		Form.duplicate(formName = "Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Copy of Form 1");
     [java] 
     [java] 		LexiconEntry.viewEntryName(rowEntry = "Form 1");
     [java] 
     [java] 		FormsAdminNavigator.gotoEditFormByName(formName = "Copy of Form 1");
     [java] 
     [java] 		Form.viewFormName(formName = "Copy of Form 1");
     [java] </code></pre></details></html>

2021-05-27 14:27 UTC, brunofariasdeo commented
Hi @lima-rafa ,
There was an sf issue that I didn't quite understood what was going on, but followed some steps and then it worked out haha.
I've resent the PR [here](https://github.com/liferay-forms/liferay-portal/pull/383).
Thanks!

2021-05-27 14:27 UTC, closed without merging

2021-05-27 18:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/8213/">test-portal-acceptance-pullrequest(master)#8213</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8213/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/274">liferay-forms#274</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535959942">[master] ci:test:relevant - lima-rafa &gt; liferay-forms - PR#274 - 2021-05-27[11:37:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/865/">publish-testray-report#865</a><br/></div></div>