LPS-131202
liferay-forms/liferay-portal pull request #334
Opened 2021-05-25 18:37 UTC by PauloVAS

2021-05-25 18:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-25 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/4322/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-source-format/builds/4322/jenkins-report.html">here</a>.</b></p>

2021-05-25 18:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7805877e041cb824d22518909441fe1b9d4cb724">7805877e041cb824d22518909441fe1b9d4cb724</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-131202">LPS-131202</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/0be12a9397cd3397e41fc05e760675e62f61983f">0be12a9397cd3397e41fc05e760675e62f61983f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4322/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4322/jenkins-report.html">here</a>.</h5></details></html>

2021-05-25 18:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4322/">test-portal-source-format#4322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/334">liferay-forms#334</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535302303">[master] ci:test:sf - PauloVAS &gt; liferay-forms - PR#334 - 2021-05-25[11:37:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/1102/">publish-testray-report#1102</a><br/></div></div>

2021-05-25 19:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9692/">test-portal-acceptance-pullrequest(master)#9692</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9692/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/334">liferay-forms#334</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535323591">[master] ci:test:relevant - PauloVAS &gt; liferay-forms - PR#334 - 2021-05-25[12:47:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/1160/">publish-testray-report#1160</a><br/></div></div>

2021-06-01 17:47 UTC, natocesarrego requested changes

2021-06-01 17:47 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormsEntries.testcase
> +		FormPortlet.submitLocalizedSuccessfully(buttonName = "Submit for Publication");
Hey @PauloVAS, the last step planned for this test is `Assert the Success Page`, but this line is just asserting that a success message is being displayed. In light of this, can you please assert that the Success Page is also being displayed?

The macro `viewSuccessPage` will do it for you. :slightly_smiling_face:

2021-06-01 17:47 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormsEntries.testcase
> +		FormsAdmin.viewFormTableBody(fieldBody = "Pending");
@PauloVAS, can you please rename:

- `viewFormTableBody` to `viewFormEntryWorkflowStatus`
- `FORM_ENTRY_TABLE_BODY` to `FORM_ENTRY_WORKFLOW_STATUS`
- `key_fieldBody` to `key_formEntryWorkflowStatus`
- `fieldBody` to `formEntryWorkflowStatus`

This renaming will make your test use the same terms used on the Forms UI and code.

Thanks in advance. :slightly_smiling_face:

2021-06-01 17:48 UTC, natocesarrego commented
@PauloVAS, can you please rebase your code against the latest master to solve the reported conflicts?

Thanks.

2021-06-01 21:02 UTC, PauloVAS commented
@natocesarrego, fixed!

2021-06-02 12:15 UTC, natocesarrego commented
Great job, @PauloVAS! :smile: :clap:

2021-06-02 12:15 UTC, natocesarrego commented
ci:forward

2021-06-02 12:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-06-02 12:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5512/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/5512/jenkins-report.html">here</a>.</b></p>

2021-06-02 12:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca00c3b11f7a6aa04d7216b586cfdac6b5e88423">ca00c3b11f7a6aa04d7216b586cfdac6b5e88423</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-131202">LPS-131202</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/3518f5aecd4a42c0871d302573856446fc5510ba">3518f5aecd4a42c0871d302573856446fc5510ba</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5512/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5512/jenkins-report.html">here</a>.</h5></details></html>

2021-06-02 12:26 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/test-portal-source-format/5512//consoleFull)

2021-06-02 12:27 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102652
[Console](https://test-1-16.liferay.com/job/test-portal-source-format/5512//consoleFull)

2021-06-02 12:27 UTC, closed without merging

2021-06-02 12:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5512/">test-portal-source-format#5512</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5512/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/334">liferay-forms#334</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537072170">[master] ci:test:sf - PauloVAS &gt; liferay-forms - PR#334 - 2021-06-02[05:15:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1027/">publish-testray-report#1027</a><br/></div></div>

2021-06-02 12:27 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/102652

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8435//consoleFull)

2021-06-02 12:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8435/">test-portal-acceptance-pullrequest(master)#8435</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8435/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/334">liferay-forms#334</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537073221">[master] ci:test:relevant - PauloVAS &gt; liferay-forms - PR#334 - 2021-06-02[05:15:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1029/">publish-testray-report#1029</a><br/></div></div>