LPS-131372
liferay-forms/liferay-portal pull request #348
Opened 2021-05-25 20:59 UTC by ewertonluna

2021-06-02 12:50 UTC, natocesarrego requested changes

2021-06-02 12:50 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsSelectFromListField.testcase
> +			var iterator = MathUtil.sum("${iterator}", "1");
@ewertonluna, does the reserved word `var` is really needed here? Won't it redeclare the variable `iterator` already declared on line **246**?

If so, can you please fix it?

2021-06-02 12:50 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/Form.macro
> +			key_fieldName = "${fieldName}",
@ewertonluna, let's rename to keep a naming consistency:

- `viewSelectFromListOnPreview` to `viewSelectFromListOptionOnPreview`
- `key_fieldName` to `key_optionValue`
- `fieldName` to `optionValue`

2021-06-02 12:50 UTC, natocesarrego commented
@ewertonluna, can you please rebase your code against the latest branch master to solve the reported conflicts?

Thanks.

2021-06-04 12:53 UTC, natocesarrego commented
OMG! Rebase conflicts again. :disappointed: 

@ewertonluna, can you please rebase against Brian's latest master?

Once you do it, feel free to trigger `ci:forward`, after all your pull looks good to go. :wink:

2021-06-04 12:54 UTC, natocesarrego commented
If your have any doubt, please let me know.

2021-06-04 19:13 UTC, pedro-michel commented
ci:forward

2021-06-04 19:13 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-06-04 19:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4834/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4834/jenkins-report.html">here</a>.</b></p>

2021-06-04 19:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0b12a0250c906f7d73addb2723c08ae57b6e7c6e">0b12a0250c906f7d73addb2723c08ae57b6e7c6e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ewertonluna/liferay-portal/tree/LPS-131372">LPS-131372</a><br/>Branch GIT ID: <a href="https://github.com/ewertonluna/liferay-portal/commit/1656f3571af7c9d9885578bc0df9e1872801e5cf">1656f3571af7c9d9885578bc0df9e1872801e5cf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4834/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4834/jenkins-report.html">here</a>.</h5></details></html>

2021-06-04 19:18 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-8.liferay.com/job/test-portal-source-format/4834//consoleFull)

2021-06-04 19:18 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102798
[Console](https://test-1-8.liferay.com/job/test-portal-source-format/4834//consoleFull)

2021-06-04 19:18 UTC, closed without merging

2021-06-04 19:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4834/">test-portal-source-format#4834</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4834/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/348">liferay-forms#348</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537725419">[master] ci:test:sf - ewertonluna &gt; liferay-forms - PR#348 - 2021-06-04[12:13:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/1164/">publish-testray-report#1164</a><br/></div></div>

2021-06-04 21:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6103//consoleFull)

2021-06-04 21:40 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2021-06-04 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6103/">test-portal-acceptance-pullrequest(master)#6103</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6103/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/348">liferay-forms#348</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537745586">[master] ci:test:relevant - ewertonluna &gt; liferay-forms - PR#348 - 2021-06-04[14:38:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/1283/">publish-testray-report#1283</a><br/></div></div>