LPS-131362
liferay-forms/liferay-portal pull request #400
Opened 2021-05-27 20:01 UTC by PauloVAS

2021-05-27 20:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-27 20:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/189/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">here</a>.</b></p>

2021-05-27 20:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cd86f84f14293db73cc1eebfe1cd3bcbce2a0ba">8cd86f84f14293db73cc1eebfe1cd3bcbce2a0ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-131362">LPS-131362</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/2be253ffb75b14166d86df445a9dd54279550378">2be253ffb75b14166d86df445a9dd54279550378</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/189/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">here</a>.</h5><pre><code>     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve xalan:xalan:2.7.2.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/10.0.0.99] failed: connect timed out
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all artifacts for configuration 'classpath'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1276)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access\$1700(DefaultConfiguration.java:142)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1838)</code></pre></details></html>

2021-05-27 20:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/189/">test-portal-source-format#189</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/400">liferay-forms#400</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1535975865">[master] ci:test:sf - PauloVAS &gt; liferay-forms - PR#400 - 2021-05-27[13:01:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/507/">publish-testray-report#507</a><br/></div></div>

2021-06-04 22:18 UTC, alinedoleron commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsSelectFromListField.testcase
> +		FormViewBuilder.setFieldRepeatable();
Hi, @PauloVAS. I noticed this macro `FormViewBuilder` belongs to AppBuilder, not to Forms. Please, can you replace this line by `FormFields.enableSwitcher(fieldName = "Repeatable")`. Thanks!

2021-06-04 22:52 UTC, alinedoleron requested changes
Hi @PauloVAS, there're two points I've commented on this PR. Please, take a look on them. =) Thanks!

Good job!

2021-06-07 20:59 UTC, PauloVAS commented
@alinedoleron, fixed!

2021-06-08 15:29 UTC, alinedoleron commented
ci:forward

2021-06-08 15:29 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-06-08 15:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/795/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/795/jenkins-report.html">here</a>.</b></p>

2021-06-08 15:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d0f6b0ff617f356c63894822b27b21f09a39fdb3">d0f6b0ff617f356c63894822b27b21f09a39fdb3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-131362">LPS-131362</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/5d3cbf3fc3204c9065e690955f71322ddcabd5de">5d3cbf3fc3204c9065e690955f71322ddcabd5de</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/795/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/795/jenkins-report.html">here</a>.</h5></details></html>

2021-06-08 15:32 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/795//consoleFull)

2021-06-08 15:32 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/102903
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/795//consoleFull)

2021-06-08 15:32 UTC, closed without merging

2021-06-08 16:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/946/">test-portal-acceptance-pullrequest(master)#946</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/946/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/400">liferay-forms#400</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538548779">[master] ci:test:relevant - PauloVAS &gt; liferay-forms - PR#400 - 2021-06-08[08:29:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2392/">publish-testray-report#2392</a><br/></div></div>

2021-06-08 16:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/795/">test-portal-source-format#795</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/795/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/400">liferay-forms#400</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538548790">[master] ci:test:sf - PauloVAS &gt; liferay-forms - PR#400 - 2021-06-08[08:29:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2393/">publish-testray-report#2393</a><br/></div></div>