LPS-133117
liferay-forms/liferay-portal pull request #458
Opened 2021-05-31 19:55 UTC by evanilson-santana

2021-05-31 19:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-05-31 19:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/2976/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-source-format/builds/2976/jenkins-report.html">here</a>.</b></p>

2021-05-31 20:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/48d8c4c22e5149acd40b01618af8598603d7117a">48d8c4c22e5149acd40b01618af8598603d7117a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-133117">LPS-133117</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/2bd444d788e58d01171b6ab72eda0e89902dd79f">2bd444d788e58d01171b6ab72eda0e89902dd79f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2976/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2976/jenkins-report.html">here</a>.</h5></details></html>

2021-05-31 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/6690/">test-portal-acceptance-pullrequest(master)#6690</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6690/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/458">liferay-forms#458</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1536675694">[master] ci:test:relevant - evanilson-santana &gt; liferay-forms - PR#458 - 2021-05-31[12:55:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/2618/">publish-testray-report#2618</a><br/></div></div>

2021-05-31 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2976/">test-portal-source-format#2976</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2976/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/458">liferay-forms#458</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1536675712">[master] ci:test:sf - evanilson-santana &gt; liferay-forms - PR#458 - 2021-05-31[12:55:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/2619/">publish-testray-report#2619</a><br/></div></div>

2021-06-08 16:11 UTC, alinedoleron commented on portal-web/test/functional/com/liferay/portalweb/macros/Form.macro
> +
Hi @evanilson-santana , I just noticed that FormViewBuilder.clickFieldLabel macro belongs to AppBuilder, not to Forms. Maybe you could try the Click function. Please, check if this example I found in some testcases is applicable to this case.

```
Click(key_name = "Numeric", locator1 = "FormFields#FIELD_TARGET_LABEL");
```
Thanks! =)

2021-06-08 16:15 UTC, alinedoleron requested changes
Hi @evanilson-santana, I've added a comment regarding the usage of App Builder macros instead of Forms product macros. This must be avoided, since App Builder folder will be deleted soon. Please, take a look on it.

Good job! =)

2021-06-08 16:17 UTC, alinedoleron commented
In addition, it seems there're some conflicts here. Please, rebase it. Thank you!

2021-06-08 19:09 UTC, evanilson-santana commented
Hi @alinedoleron All test steps are running correctly, I updated the macro for the specific test.

2021-06-08 20:48 UTC, alinedoleron commented
Good job, @evanilson-santana! Please, could you generate a new index.html to put in the related [Jira ticket](https://issues.liferay.com/browse/LPS-133117)? Just for keep the tracking of the executions =) After this, I'll forward the PR. Thank you very much!

2021-06-08 21:10 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-06-08 21:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/828/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/828/jenkins-report.html">here</a>.</b></p>

2021-06-08 21:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/527463063f68d983c5aeeb237681248b239c023d">527463063f68d983c5aeeb237681248b239c023d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-133117">LPS-133117</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/c8b60150d346057e94f5630361795f3dd2c8d605">c8b60150d346057e94f5630361795f3dd2c8d605</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/828/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/828/jenkins-report.html">here</a>.</h5></details></html>

2021-06-08 21:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/828//consoleFull)

2021-06-08 21:13 UTC, closed without merging

2021-06-08 21:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/828/">test-portal-source-format#828</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/828/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/458">liferay-forms#458</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538589350">[master] ci:test:sf - evanilson-santana &gt; liferay-forms - PR#458 - 2021-06-08[14:10:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2451/">publish-testray-report#2451</a><br/></div></div>

2021-06-08 22:11 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/979//consoleFull)

2021-06-08 22:11 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2021-06-08 22:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/979/">test-portal-acceptance-pullrequest(master)#979</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/979/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/458">liferay-forms#458</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538590451">[master] ci:test:relevant - evanilson-santana &gt; liferay-forms - PR#458 - 2021-06-08[15:09:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2469/">publish-testray-report#2469</a><br/></div></div>