LPS-133781
liferay-forms/liferay-portal pull request #581
Opened 2021-06-10 20:21 UTC by MoryAlvesBR

2021-06-10 20:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/5077/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">here</a>.</b></p>

2021-06-10 20:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9aa7c90f803b4c2ba6a2f461bae2a97c67c218ea">9aa7c90f803b4c2ba6a2f461bae2a97c67c218ea</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MoryAlvesBR/liferay-portal/tree/LPS-133781">LPS-133781</a><br/>Branch GIT ID: <a href="https://github.com/MoryAlvesBR/liferay-portal/commit/bb338883c5c5fe4da99d5845fc69c8b95ac5436e">bb338883c5c5fe4da99d5845fc69c8b95ac5436e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5077/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormsPreview.testcase expected:&lt;..."Form - Forms");
     [java] 
     [java] 		[FormPortletConfiguration.viewTranslationLanguage(symbolName = "en-US");
     [java] 
     [java] 		FormFields.viewLabel(
     [java] 			fieldLabel = "Text",
     [java] 			fieldName = "Text");
     [java] 
     [java] 		FormPortletConfiguration.changeLanguageTo(changeLanguageTo = "en-US");
     [java] 
     [java] 		FormPortletConfiguration.changeLanguageTo(changeLanguageTo = "espa??ol-Espa??a");
     [java] 
     [java] 		FormFields.viewLabel(
     [java] 			fieldLabel = "Texto",
     [java] 			fieldName = "Texto");]
     [java] 	\}
     [java] 
     [java] 	@description =...&gt; but was:&lt;..."Form - Forms");
     [java] 
     [java] 		[
     [java] 		FormPortletConfiguration.viewTranslationLanguage(symbolName = "en-US");
     [java] 		
     [java] 		FormFields.viewLabel(
     [java] 			fieldLabel = "Text",
     [java] 			fieldName = "Text");
     [java] 
     [java] 		FormPortletConfiguration.changeLanguageTo(changeLanguageTo = "en-US");
     [java] 
     [java] 		FormPortletConfiguration.changeLanguageTo(changeLanguageTo = "espa??ol-Espa??a");
     [java] 
     [java] 		FormFields.viewLabel(
     [java] 			fieldLabel = "Texto",
     [java] 			fieldName = "Texto");
     [java] ]
     [java] 	\}
     [java] 
     [java] 	@description =...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:483)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:312)
[stopwatch] [run.batch.test.action: 1:45.441 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-14/job/test-portal-source-format/5077//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210610132455808.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210610132455808.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.</code></pre></details></html>

2021-06-10 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5077/">test-portal-source-format#5077</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/581">liferay-forms#581</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1539231328">[master] ci:test:sf - MoryAlvesBR &gt; liferay-forms - PR#581 - 2021-06-10[13:21:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/1074/">publish-testray-report#1074</a><br/></div></div>

2021-06-15 19:41 UTC, wesleyroberts commented
The macro's FormPortletConfiguration.changeLanguageTo and FormPortletConfiguration.viewTranslationLanguage , need changes.

2021-06-15 19:44 UTC, wesleyroberts commented on portal-web/test/functional/com/liferay/portalweb/macros/FormPortletConfiguration.macro
> +	}
Change ${symbolName} for ${language}.

2021-06-15 19:44 UTC, wesleyroberts commented on portal-web/test/functional/com/liferay/portalweb/macros/FormPortletConfiguration.macro
> +	macro changeLanguageTo {
Change this macro for macro
 changeLanguageTo {
		Click(
			changeLanguageTo = "${getLanguage}",
			locator1 = "FormPortletConfiguration#SELECT_LANGUAGE");
		Click(
			changeLanguageTo = "${changeLanguageTo}",
			locator1 = "FormPortletConfiguration#SELECT_LANGUAGE");
	}

2021-06-16 18:53 UTC, natocesarrego commented
@wesleyroberts and @MoryAlvesBR, new changes were requested on https://github.com/liferay-forms/liferay-portal/pull/558, please apply them here.

Thanks.

2021-06-18 11:58 UTC, natocesarrego commented
@MoryAlvesBR, can you please rebase your code against to the latest branch master of Brian Chan's repo to solve the reported conflicts?

Thanks.

2021-06-18 12:02 UTC, natocesarrego requested changes

2021-06-18 12:02 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormsPreview.testcase
> +		Form.editElementSetFieldLabel(fieldValue = "Texto");
@MoryAlvesBR, you should use the macro to change the Field Label and not the Element Set Field Label, can you please fix it?

2021-06-28 13:23 UTC, natocesarrego commented
@MoryAlvesBR, please run SF locally, because this pull have SF issues. Moreover, please put together all you changes in a single commit.

Thanks

2021-06-29 20:56 UTC, natocesarrego commented
ci:forward

2021-06-29 20:56 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-06-29 20:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/3220/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/3220/jenkins-report.html">here</a>.</b></p>

2021-06-29 21:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/167f47e46c2ea38101a1cfbf6d2ba237e138b484">167f47e46c2ea38101a1cfbf6d2ba237e138b484</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MoryAlvesBR/liferay-portal/tree/LPS-133781">LPS-133781</a><br/>Branch GIT ID: <a href="https://github.com/MoryAlvesBR/liferay-portal/commit/f28c23f96f0bb0ad045e7649ecbdfca6fa0f02f9">f28c23f96f0bb0ad045e7649ecbdfca6fa0f02f9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3220/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3220/jenkins-report.html">here</a>.</h5></details></html>

2021-06-29 21:00 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-15.liferay.com/job/test-portal-source-format/3220//consoleFull)

2021-06-29 21:01 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/103781
[Console](https://test-1-15.liferay.com/job/test-portal-source-format/3220//consoleFull)

2021-06-29 21:01 UTC, closed without merging

2021-06-29 21:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4566/">test-portal-acceptance-pullrequest(master)#4566</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4566/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/581">liferay-forms#581</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1543706051">[master] ci:test:relevant - MoryAlvesBR &gt; liferay-forms - PR#581 - 2021-06-29[13:57:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/1362/">publish-testray-report#1362</a><br/></div></div>

2021-06-29 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3220/">test-portal-source-format#3220</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3220/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/581">liferay-forms#581</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1543706060">[master] ci:test:sf - MoryAlvesBR &gt; liferay-forms - PR#581 - 2021-06-29[13:57:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/1363/">publish-testray-report#1363</a><br/></div></div>