LPS-134377
liferay-forms/liferay-portal pull request #690
Opened 2021-06-25 19:25 UTC by Diogomes

2021-06-25 19:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-06-25 19:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1852/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/1852/jenkins-report.html">here</a>.</b></p>

2021-06-25 19:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5910ce2c745a8088cfcde5fc40a9f648c48b28e">d5910ce2c745a8088cfcde5fc40a9f648c48b28e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Diogomes/liferay-portal/tree/LPS-134377">LPS-134377</a><br/>Branch GIT ID: <a href="https://github.com/Diogomes/liferay-portal/commit/60cbd4e871eece0e6c0e14dd4629aa2ca310410e">60cbd4e871eece0e6c0e14dd4629aa2ca310410e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1852/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1852/jenkins-report.html">here</a>.</h5></details></html>

2021-06-25 19:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1852/">test-portal-source-format#1852</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1852/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/690">liferay-forms#690</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1542849060">[master] ci:test:sf - Diogomes &gt; liferay-forms - PR#690 - 2021-06-25[12:27:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/5438/">publish-testray-report#5438</a><br/></div></div>

2021-06-25 19:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2017/">test-portal-acceptance-pullrequest(master)#2017</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2017/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/690">liferay-forms#690</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1542857943">[master] ci:test:relevant - Diogomes &gt; liferay-forms - PR#690 - 2021-06-25[12:37:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/5441/">publish-testray-report#5441</a><br/></div></div>

2021-07-07 18:25 UTC, natocesarrego commented
@Diogomes, the uploaded `index.html` on the Jira ticket doesn't provide the test execution duration neither if it passed or not, can you please check it and fix?

2021-07-07 18:33 UTC, Diogomes commented
> @Diogomes , o upload `index.html`no tíquete do Jira não fornece a duração da execução do teste nem se passou ou não, você pode verificar e corrigir?

Yes I Can

2021-07-07 18:33 UTC, natocesarrego requested changes

2021-07-07 18:33 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormRules.testcase
> +			fieldType = "Text");
@Diogomes, please add a line break after this line

2021-07-07 18:33 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormRules.testcase
> +			value = "Is empty");
@Diogomes, can you please use the existing macros instead, like `FormRules.viewConditionFieldSummary`?

Please take a look on the macros available on `FormRules.macro`. :wink:

2021-07-09 13:31 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormRules.testcase
> +		FormRules.viewConfigureRules(
@Diogomes, can we create two separated macros instead? Ideally, one will check the condition and the other one will check the action.

2021-07-09 17:28 UTC, Diogomes commented
@natocesarrego  All done . 😄

2021-07-09 20:27 UTC, natocesarrego requested changes

2021-07-09 20:27 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +	macro viewBuilderRuleAction {
@Diogomes, please rename to `viewRuleBuilderAction` to keep consistency with the name used in the UI and in the path `RULE_BUILDER_FIELD_GENERIC`

2021-07-09 20:27 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +	macro viewBuilderRuleCondition {
@Diogomes, please rename to `viewRuleBuilderCondition` to keep consistency with the name used in the UI and in the path `RULE_BUILDER_FIELD_GENERIC`

2021-07-09 20:27 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormRules.testcase
> +			value = "Is empty");
@Diogomes, let's perform the assertion of the whole condition then we perform the assertion of the whole action, like below:
```
FormRules.viewBuilderRuleCondition(
    positionNumber = "1",
    value = "Text");

FormRules.viewBuilderRuleCondition(
    positionNumber = "2",
    value = "Is empty");

FormRules.viewBuilderRuleAction(
    positionNumber = "1",
    value = "Require");

FormRules.viewBuilderRuleAction(
    positionNumber = "2",
    value = "Text");
```

2021-07-14 20:21 UTC, natocesarrego commented
ci:forward

2021-07-14 20:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-14 20:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5079/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/5079/jenkins-report.html">here</a>.</b></p>

2021-07-14 20:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dddb583ee0936c473b17bbb24292657016dbf757">dddb583ee0936c473b17bbb24292657016dbf757</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Diogomes/liferay-portal/tree/LPS-134377">LPS-134377</a><br/>Branch GIT ID: <a href="https://github.com/Diogomes/liferay-portal/commit/a6a90fe65bf638003a95fd5813cde9f1ebb87d74">a6a90fe65bf638003a95fd5813cde9f1ebb87d74</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5079/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5079/jenkins-report.html">here</a>.</h5></details></html>

2021-07-14 20:25 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/5079//consoleFull)

2021-07-14 20:25 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104365
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/5079//consoleFull)

2021-07-14 20:25 UTC, closed without merging

2021-07-14 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5079/">test-portal-source-format#5079</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5079/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/690">liferay-forms#690</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547145739">[master] ci:test:sf - Diogomes &gt; liferay-forms - PR#690 - 2021-07-14[13:21:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/1936/">publish-testray-report#1936</a><br/></div></div>

2021-07-14 20:49 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/6091//consoleFull)

2021-07-14 20:49 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2021-07-14 20:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/6091/">test-portal-acceptance-pullrequest(master)#6091</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6091/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/690">liferay-forms#690</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547147459">[master] ci:test:relevant - Diogomes &gt; liferay-forms - PR#690 - 2021-07-14[13:47:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/1600/">publish-testray-report#1600</a><br/></div></div>