LPS-134381
liferay-forms/liferay-portal pull request #693
Opened 2021-06-25 20:38 UTC by lima-rafa

2021-06-25 20:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-06-25 20:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/6071/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-source-format/builds/6071/jenkins-report.html">here</a>.</b></p>

2021-06-25 20:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 54 seconds</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5910ce2c745a8088cfcde5fc40a9f648c48b28e">d5910ce2c745a8088cfcde5fc40a9f648c48b28e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-134381">LPS-134381</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/305caacabf479b3a23312709b1cd0ef8b2f31f96">305caacabf479b3a23312709b1cd0ef8b2f31f96</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6071/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6071/jenkins-report.html">here</a>.</h5><pre><code>	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at net.sf.antcontrib.logic.TryCatchTask.execute(TryCatchTask.java:207)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[beanshell] Created cache file in /tmp/jenkins-cached-files/-2066032430.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:13421: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-source-format.xml:18: Sourced file: inline evaluation of: `` 			 				import com.liferay.jenkins.results.parser.AntUtil; 				import com.lifer . . . '' : TargetError : at Line: 345 : in file: inline evaluation of: `` 			 				import com.liferay.jenkins.results.parser.AntUtil; 				import com.lifer . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: Unable to create local branch lima-rafa-693-LPS-134381 at 8487f813434e5f1c0af5b5b09bfb8d7c06dde11f
fatal: Not a valid branch point: '8487f813434e5f1c0af5b5b09bfb8d7c06dde11f'.</code></pre></details></html>

2021-06-25 20:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6071/">test-portal-source-format#6071</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6071/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/693">liferay-forms#693</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1542879379">[master] ci:test:sf - lima-rafa &gt; liferay-forms - PR#693 - 2021-06-25[13:40:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/1528/">publish-testray-report#1528</a><br/></div></div>

2021-07-07 18:47 UTC, natocesarrego commented
@lima-rafa, can you please rebase your code against to the latest branch master of Brian Chan's repo to solve the reported conflicts?

Thanks.

2021-07-09 20:43 UTC, natocesarrego requested changes

2021-07-09 20:43 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +		var key_conditionOperator = "${conditionOperator}";
@lima-rafa, please sort alphabetically.

2021-07-09 20:43 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +		var key_conditionOperator = "${conditionOperator}";
@lima-rafa, please sort alphabetically.

2021-07-09 20:43 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +		var key_conditionOperator = "${conditionOperator}";
@lima-rafa, please sort alphabetically.

2021-07-09 20:43 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/macros/FormRules.macro
> +		}
@lima-rafa, apparently, this is not necessary for this test, right? If so, can you please remove this code and the path `FormRules#RULE_BUILDER_SUMMARY_CONDITION_EXTENDED`?

2021-07-13 17:08 UTC, lima-rafa commented
@natocesarrego Alterado

2021-07-14 18:43 UTC, natocesarrego commented
ci:forward

2021-07-14 18:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-14 18:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/4524/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-source-format/builds/4524/jenkins-report.html">here</a>.</b></p>

2021-07-14 18:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0b91010c2ef77d4c61a3b74503d0220f88be8f04">0b91010c2ef77d4c61a3b74503d0220f88be8f04</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lima-rafa/liferay-portal/tree/LPS-134381">LPS-134381</a><br/>Branch GIT ID: <a href="https://github.com/lima-rafa/liferay-portal/commit/21f2cba4677a75d705d2345bf6b771fa7763bfd3">21f2cba4677a75d705d2345bf6b771fa7763bfd3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4524/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4524/jenkins-report.html">here</a>.</h5></details></html>

2021-07-14 18:47 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-13.liferay.com/job/test-portal-source-format/4524//consoleFull)

2021-07-14 18:47 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104351
[Console](https://test-1-13.liferay.com/job/test-portal-source-format/4524//consoleFull)

2021-07-14 18:47 UTC, closed without merging

2021-07-14 18:47 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/104351

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2915//consoleFull)

2021-07-14 18:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4524/">test-portal-source-format#4524</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4524/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/693">liferay-forms#693</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547117034">[master] ci:test:sf - lima-rafa &gt; liferay-forms - PR#693 - 2021-07-14[11:43:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/1701/">publish-testray-report#1701</a><br/></div></div>

2021-07-14 18:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2915/">test-portal-acceptance-pullrequest(master)#2915</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2915/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/693">liferay-forms#693</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547117810">[master] ci:test:relevant - lima-rafa &gt; liferay-forms - PR#693 - 2021-07-14[11:43:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8092/">publish-testray-report#8092</a><br/></div></div>