LRQA-68317
liferay-forms/liferay-portal pull request #911
Opened 2021-09-08 16:53 UTC by leticiachiu

2021-09-08 16:53 UTC, liferay-forms commented
ci:test:sf

2021-09-08 16:53 UTC, liferay-forms commented
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

2021-09-08 16:53 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-08 16:53 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-08 16:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/197/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/197/jenkins-report.html">here</a>.</b></p>

2021-09-08 16:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/48e4072e6edeac08efa2e38f65cf9bbbdcc44c7a">48e4072e6edeac08efa2e38f65cf9bbbdcc44c7a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LRQA-68317">LRQA-68317</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/52306581c5483275e77a988f1df21b6b2f0135ed">52306581c5483275e77a988f1df21b6b2f0135ed</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/197/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/197/jenkins-report.html">here</a>.</h5></details></html>

2021-09-08 16:55 UTC, liferay-forms commented
ci:test:relevant

2021-09-08 16:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/197/">test-portal-source-format#197</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/197/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/911">liferay-forms#911</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1559785138">[master] ci:test:sf - leticiachiu &gt; liferay-forms - PR#911 - 2021-09-08[09:53:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/650/">publish-testray-report#650</a><br/></div></div>

2021-09-08 16:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/207/">test-portal-acceptance-pullrequest(master)#207</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/207/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/911">liferay-forms#911</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1559785147">[master] ci:test:relevant - leticiachiu &gt; liferay-forms - PR#911 - 2021-09-08[09:56:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/651/">publish-testray-report#651</a><br/></div></div>

2021-09-09 13:57 UTC, natocesarrego requested changes
Terrific pull, @leticiachiu! :smile: :tada: 

Please see my tiny SF comments. Keep this good work and soon I'll jump out from the review of your pulls. :wink:

2021-09-09 13:57 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsNumericField.testcase
> +	@description = "LPS-125861 - Verify that the Input Mask can be enabled on intergers"
@leticiachiu, misspelling in word **integers**

2021-09-09 13:57 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsNumericField.testcase
> +		Click(locator1 = "FormFields#CHARACTER_OPTIONS_SHOW_MORE_BUTTON");
@leticiachiu, can you please add a line break?

2021-09-09 13:57 UTC, natocesarrego commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsNumericField.testcase
> +	@description = "LPS-130848 - Verify that the Input Mask can be applied on intergers"
@leticiachiu, misspelling in word **integers**

2021-09-09 16:17 UTC, leticiachiu commented
Fixed. Thanksss @natocesarrego! :smiling_face_with_three_hearts::sparkling_heart:

2021-09-10 21:05 UTC, natocesarrego commented
ci:forward

2021-09-10 21:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-10 21:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/164/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/164/jenkins-report.html">here</a>.</b></p>

2021-09-10 21:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c406508139ee68d8938a2076c9afa7e56bb47b38">c406508139ee68d8938a2076c9afa7e56bb47b38</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/LRQA-68317">LRQA-68317</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/ee888c6a04e0cabf368cb9052cbb8bf1de7c6657">ee888c6a04e0cabf368cb9052cbb8bf1de7c6657</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/164/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/164/jenkins-report.html">here</a>.</h5></details></html>

2021-09-10 21:08 UTC, liferay-forms commented
ci:test:relevant

2021-09-10 21:09 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/164//consoleFull)

2021-09-10 21:09 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107008
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/164//consoleFull)

2021-09-10 21:09 UTC, closed without merging

2021-09-10 21:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/164/">test-portal-source-format#164</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/164/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/911">liferay-forms#911</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560365428">[master] ci:test:sf - leticiachiu &gt; liferay-forms - PR#911 - 2021-09-10[14:06:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/537/">publish-testray-report#537</a><br/></div></div>

2021-09-10 21:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/178/">test-portal-acceptance-pullrequest(master)#178</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/178/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/911">liferay-forms#911</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560366153">[master] ci:test:relevant - leticiachiu &gt; liferay-forms - PR#911 - 2021-09-10[14:06:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/557/">publish-testray-report#557</a><br/></div></div>

2021-09-10 21:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/143/">test-portal-acceptance-pullrequest(master)#143</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/143/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/911">liferay-forms#911</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560366171">[master] ci:test:relevant - leticiachiu &gt; liferay-forms - PR#911 - 2021-09-10[14:09:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/403/">publish-testray-report#403</a><br/></div></div>