LRQA 69446
liferay-forms/liferay-portal pull request #916
Opened 2021-09-09 14:53 UTC by guivilarim

- LRQA-69446 Add tests stubs
- LRQA-69446 Create BUTTON_LABEL_INDEXED and SELECTOR_INPUT_INDEXED paths
- LRQA-69446 Create inputDataInUploadField and assertDataInUploadField macros
- LRQA-69446 Add CanInputData test
- LRQA-69446 Fix CanClearImage test
- LRQA-69446 Create assertUploadNotPresent macro
- LRQA-69446 Add CanClearInput test
- LRQA-69446 Add CanNotPublishBlankRequiredField test
- LRQA-69446 Add CanRemoveDuplicatedField test
- LRQA-69446 Add CanInputDataOnDuplicatedField test
- LRQA-69446 Fix CanClearInput test

2021-09-09 14:53 UTC, liferay-forms commented
ci:test:sf

2021-09-09 14:53 UTC, liferay-forms commented
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

2021-09-09 14:53 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-09 14:53 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-09 14:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/217/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/217/jenkins-report.html">here</a>.</b></p>

2021-09-09 14:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22faa314dbdd0b43bc2441e96f7f7426ae6aa43b">22faa314dbdd0b43bc2441e96f7f7426ae6aa43b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-69446">LRQA-69446</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/2c5b90925df59dd351e5371744a5c3dfa606868d">2c5b90925df59dd351e5371744a5c3dfa606868d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/217/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/217/jenkins-report.html">here</a>.</h5></details></html>

2021-09-09 14:56 UTC, liferay-forms commented
ci:test:relevant

2021-09-09 15:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/217/">test-portal-source-format#217</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/217/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/916">liferay-forms#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560139704">[master] ci:test:sf - guivilarim &gt; liferay-forms - PR#916 - 2021-09-09[07:53:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/706/">publish-testray-report#706</a><br/></div></div>

2021-09-09 15:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/229/">test-portal-acceptance-pullrequest(master)#229</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/229/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/916">liferay-forms#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560141469">[master] ci:test:relevant - guivilarim &gt; liferay-forms - PR#916 - 2021-09-09[07:56:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/707/">publish-testray-report#707</a><br/></div></div>

2021-09-09 15:12 UTC, guivilarim commented
ci:test:sf

2021-09-09 15:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/225/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/225/jenkins-report.html">here</a>.</b></p>

2021-09-09 15:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22faa314dbdd0b43bc2441e96f7f7426ae6aa43b">22faa314dbdd0b43bc2441e96f7f7426ae6aa43b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-69446">LRQA-69446</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/22a8a5109727f662ff06df7c3ab78d499256da65">22a8a5109727f662ff06df7c3ab78d499256da65</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/225/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/225/jenkins-report.html">here</a>.</h5></details></html>

2021-09-09 15:15 UTC, liferay-forms commented
ci:test:relevant

2021-09-09 15:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/225/">test-portal-source-format#225</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/225/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/916">liferay-forms#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560143853">[master] ci:test:sf - guivilarim &gt; liferay-forms - PR#916 - 2021-09-09[08:12:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/770/">publish-testray-report#770</a><br/></div></div>

2021-09-09 15:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/316/">test-portal-acceptance-pullrequest(master)#316</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/316/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/916">liferay-forms#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560144572">[master] ci:test:relevant - guivilarim &gt; liferay-forms - PR#916 - 2021-09-09[08:15:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/1010/">publish-testray-report#1010</a><br/></div></div>

2021-09-13 12:16 UTC, natocesarrego requested changes
@guivilarim, I'm able to see an evolution from your previous pull though I also realized some unnecessary content being committed. Please visit my review comments and get back to me if you have ANY question. If you also need some assistance regarding Git, please let me know and I'll be glad to help you. :wink: 

Thanks!

2021-09-13 12:16 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEImageField.testcase
> +		DERenderer.clearField(fieldLabel = "Image");
@guivilarim, why did you decide to fix a test inside a pull request intended to create new tests only? Was this fix mandatory to the tests being created by this pull succeed? If not, honestly, I believe that we should create a specific pull to tackle the test fix.

2021-09-13 12:16 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/macros/DERenderer.macro
> -
@guivilarim, the commit message is inconsistent with the commit content, can you please revisit this commit?

2021-09-13 12:16 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEUploadField.testcase
> +	test {
@guivilarim, where is the test name??

2021-09-17 11:28 UTC, natocesarrego commented
@guivilarim, let's talk about this pull today after our daily. :wink: Please remind me about it at the end of our meeting.

2021-09-21 12:03 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/paths/DataEngineRenderer.path
> +	<td>xpath=(//label[normalize-space(text())='${key_fieldLabel}']/following-sibling::div//div[contains(@class,'input-group')]//input[not(contains(@type,'hidden'))])[${index}]</td>
@guivilarim, the variables `text` and `index` are still missing the prefix `key_`, can you please add it?

Thanks

2021-09-21 12:10 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEUploadField.testcase
> +	test {
@guivilarim, have you had the chance to see this comment? Can you please edit this commit to make it clearer to the reviewer?

2021-09-22 13:34 UTC, natocesarrego commented
ci:forward

2021-09-22 13:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5765/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/5765/jenkins-report.html">here</a>.</b></p>

2021-09-22 13:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/851972f4b54bfbb3174c879c0412cb35c578a6ca">851972f4b54bfbb3174c879c0412cb35c578a6ca</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-69446">LRQA-69446</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/b5214245a59fd89981c89870a494991be0d24628">b5214245a59fd89981c89870a494991be0d24628</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5765/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5765/jenkins-report.html">here</a>.</h5></details></html>

2021-09-22 13:42 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/test-portal-source-format/5765//consoleFull)

2021-09-22 13:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107590
[Console](https://test-1-16.liferay.com/job/test-portal-source-format/5765//consoleFull)

2021-09-22 13:43 UTC, closed without merging

2021-09-22 14:18 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/107590

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8682//consoleFull)

2021-09-22 14:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8682/">test-portal-acceptance-pullrequest(master)#8682</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8682/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/916">liferay-forms#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1563102285">[master] ci:test:relevant - guivilarim &gt; liferay-forms - PR#916 - 2021-09-22[07:04:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1745/">publish-testray-report#1745</a><br/></div></div>