LRQA 70033
liferay-forms/liferay-portal pull request #956
Opened 2021-09-23 04:32 UTC by guivilarim

- LRQA-70033 Create test stubs
- LRQA-70033 Create assertWebContentNotPresent, assertDataInWebContentField and inputDataInWebContentField macros
- LRQA-70033 Add CanInputLink test
- LRQA-70033 Add CanClearInput test
- LRQA-70033 Add CanNotPublishBlankRequiredField test
- LRQA-70033 Add CanRemoveDuplicatedField test
- LRQA-70033 Add CanInputDataOnDuplicatedField test
- LRQA-70033 Add test descriptions

2021-09-23 04:32 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-23 04:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-28 20:07 UTC, natocesarrego requested changes

2021-09-28 20:07 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEWebContentField.testcase
> +		DERenderer.clearImageField(fieldLabel = "Web Content");
@guivilarim, I think it's time to rename this macro, after all you're cleaning a Web Content Field and not an Image Field.

2021-09-28 20:07 UTC, natocesarrego commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEWebContentField.testcase
> +	@description = "This is a test for LRQA-70033. This test verifies that is possible to link an Web Content"
@guivilarim, what exactly do you mean with **link an Web Content**? Can you please clarify?

2021-09-30 13:05 UTC, natocesarrego commented
Good job, @guivilarim! :slightly_smiling_face:

2021-09-30 13:05 UTC, natocesarrego commented
ci:forward

2021-09-30 13:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-30 13:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/213/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com//userContent/jobs/test-portal-source-format/builds/213/jenkins-report.html">here</a>.</b></p>

2021-09-30 13:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fda430587b0211e362c69c5b387d9db14490ca89">fda430587b0211e362c69c5b387d9db14490ca89</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guivilarim/liferay-portal/tree/LRQA-70033">LRQA-70033</a><br/>Branch GIT ID: <a href="https://github.com/guivilarim/liferay-portal/commit/ff7e18cb849b3a6804f85974d751914fbc4eb5ef">ff7e18cb849b3a6804f85974d751914fbc4eb5ef</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/213/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/213/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/data-engine/data-engine-test/src/testFunctional/tests/fields/DEWebContentField.testcase expected:&lt;...WebContentField(
     [java] 			[contentName = "Web Content Title 1",
     [java] 			fieldLabel = "Web Content");
     [java] 
     [java] 		Button.clickPublish();
     [java] 
     [java] 		WebContentNavigator.gotoEditCP(webContentTitle = "Web Content Title");
     [java] 
     [java] 		DERenderer.clearDataOnField(fieldLabel = "Web Content");
     [java] 
     [java] 		Button.clickPublish();
     [java] 
     [java] 		WebContentNavigator.gotoEditCP(webContentTitle = "Web Content Title");
     [java] 
     [java] 		DERenderer.assertWebContentNotPresent(
     [java] 			contentName = "Web Content Title 1",
     [java] 			fieldLabel = "Web Content");
     [java] 	\}
     [java] 
     [java] 	@description = "This is a test for LRQA-68658. This test verifies that Label and Help text can be edited."
     [java] 	@priority = "5"
     [java] 	test CanEditLabelAndHelpText \{
     [java] 		NavItem.gotoStructures();
     [java] 
     [java] 		WebContentStructures.addCP(structureName = "WC Structure Title");
     [java] 
     [java] 		DataEngine.addField(
     [java] 			fieldFieldLabel = "Web Content",
     [java] 			fieldName = "Web Content");
     [java] 
     [java] 		DataEngine.editFieldTip(
     [java] 			fieldFieldLabel = "Web Content",
     [java] 			fieldHelp = "Help Text");
     [java] 
     [java] 		WebContentStructures.saveCP();
     [java] 
     [java] 		WebContentNavigator.gotoEditStructure(structureName = "WC Structure Title");
     [java] 
     [java] 		DataEngine.editFieldLabel(
     [java] 			fieldFieldLabel = "Web Content",
     [java] 			fieldFieldLabelEdit = "Web Content Edited");
     [java] 
     [java] 		DataEngine.editFieldTip(
     [java] 			fieldFieldLabel = "Web Content Edited",
     [java] 			fieldHelp = "Help Text Edited");
     [java] 
     [java] 		WebContentStructures.saveCP();
     [java] 
     [java] 		WebContentNavigator.gotoEditStructure(structureName = "WC Structure Title");
     [java] 
     [java] 		DataEngine.viewField(
     [java] 			fieldFieldLabel = "Web Content Edited",
     [java] 			fieldHelp = "Help Text Edited",
     [java] 			fieldName = "Web Content");
     [java] 	\}
     [java] </code></pre></details></html>

2021-09-30 13:47 UTC, liferay-forms commented
Hey @guivilarim, can you please fix the source formatter issues and resend? Thanks

2021-09-30 13:47 UTC, closed without merging

2021-09-30 14:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/213/">test-portal-source-format#213</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/213/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/956">liferay-forms#956</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565343790">[master] ci:test:sf - guivilarim &gt; liferay-forms - PR#956 - 2021-09-30[06:06:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/728/">publish-testray-report#728</a><br/></div></div>

2021-09-30 14:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/265/">test-portal-acceptance-pullrequest(master)#265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/956">liferay-forms#956</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565344081">[master] ci:test:relevant - guivilarim &gt; liferay-forms - PR#956 - 2021-09-30[06:06:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/731/">publish-testray-report#731</a><br/></div></div>