LPS-139879 modifying the mailing by headless-form
liferay-forms/liferay-portal pull request #972
Opened 2021-09-28 15:04 UTC by antonio91dev

2021-09-28 15:04 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-28 16:38 UTC, carolmariaabb commented
ci:test:sf

2021-09-28 16:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/346/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/346/jenkins-report.html">here</a>.</b></p>

2021-09-28 16:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b54959f696b11eef812dd034ba7421a9c6beef75">b54959f696b11eef812dd034ba7421a9c6beef75</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/antonio91dev/liferay-portal/tree/LPS-139879">LPS-139879</a><br/>Branch GIT ID: <a href="https://github.com/antonio91dev/liferay-portal/commit/2e9b6cd1d2e0a5d1e918389f1e45beed993412c2">2e9b6cd1d2e0a5d1e918389f1e45beed993412c2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/346/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/346/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/notification/DDMFormEmailNotificationSender.java expected:&lt;...reateMailMessage(
     [java] 		[	ServiceContext serviceContext,
     [java] 			DDMFormInstanceRecord ddmFormInstanceRecord)
     [java] 		throws Exception \{
     [java] 
     [java] 		DDMFormInstance ddmFormInstance =
     [java] 			ddmFormInstanceRecord.getFormInstance();
     [java] 
     [java] 		InternetAddress fromInternetAddress = new InternetAddress(
     [java] 			getEmailFromAddress(ddmFormInstance),
     [java] 			getEmailFromName(ddmFormInstance));
     [java] 
     [java] 		String subject = getEmailSubject(ddmFormInstance);
     [java] 
     [java] 		String body = getEmailBody(
     [java] 			serviceContext, ddmFormInstance, ddmFormInstanceRecord);
     [java] 
     [java] 		MailMessage mailMessage = new MailMessage(
     [java] 			fromInternetAddress, subject, body, true);
     [java] 
     [java] 		InternetAddress[] toAddresses = InternetAddress.parse(
     [java] 			getEmailToAddress(ddmFormInstance));
     [java] 
     [java] 		mailMessage.setTo(toAddresses);
     [java] 
     [java] 		return mailMessage;
     [java] 	\}
     [java] 
     [java] 	protected Template createTemplate(
     [java] 			ServiceContext serviceContext, DDMFormInstance ddmFormInstance,
     [java] 			DDMFormInstanceRecord ddmFormInstanceRecord)
     [java] 		throws PortalException \{
     [java] 
     [java] 		Template template = TemplateManagerUtil.getTemplate(
     [java] 			TemplateConstants.LANG_TYPE_FTL,
     [java] 			getTemplateResource(_TEMPLATE_PATH), false);
     [java] 
     [java] 		populateParameters(
     [java] 			template, serviceContext, ddmFormInstance, ddmFormInstanceRecord);
     [java] 
     [java] 		return template;
     [java] 	\}
     [java] 
     [java] 	protected DDMForm getDDMForm(DDMFormInstance ddmFormInstance)
     [java] 		throws PortalException \{
     [java] 
     [java] 		DDMStructure ddmStructure = ddmFormInstance.getStructure();
     [java] 
     [java] 		return ddmStructure.getDDMForm();
     [java] 	\}
     [java] 
     [java] 	protected DDMFormField getDDMFormField(
     [java] 		List&lt;DDMFormFieldValue&gt; ddmFormFieldValues) \{
     [java] 
     [java] 		DDMFormFieldValue ddmFormFieldValue = ddmFormFieldValues.get(0);
     [java] </code></pre></details></html>

2021-09-28 16:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/346/">test-portal-source-format#346</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/346/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1564830163">[master] ci:test:sf - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-28[09:38:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1088/">publish-testray-report#1088</a><br/></div></div>

2021-09-28 16:42 UTC, carolmariaabb requested changes
@antonio91dev please see my comments below. In addition, can you please fix the source formatter issues? 
Thanks

2021-09-28 16:42 UTC, carolmariaabb commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/notification/DDMFormEmailNotificationSender.java
> +			DDMFormInstance ddmFormInstance, ServiceContext serviceContext)
@antonio91dev please order the parameters to be consistent with the other methods `getEmailBody`, `createTemplate`, `createMailMessage` and `populateParameters `.

2021-09-28 16:42 UTC, carolmariaabb commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/notification/DDMFormEmailNotificationSender.java
> +			ServiceContext serviceContext)
@antonio91dev please order the parameters to be consistent with the other methods `getEmailBody`, `createTemplate`, `createMailMessage` and `populateParameters `.

2021-09-28 17:40 UTC, antonio91dev commented
@carolmariaabb  a new commit was added applying the changes

2021-09-28 20:40 UTC, carolmariaabb commented
ci:test:sf

2021-09-28 20:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/361/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">here</a>.</b></p>

2021-09-28 20:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/07358e14977aacb4ffc6ffab0a3cfb42032d0002">07358e14977aacb4ffc6ffab0a3cfb42032d0002</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/antonio91dev/liferay-portal/tree/LPS-139879">LPS-139879</a><br/>Branch GIT ID: <a href="https://github.com/antonio91dev/liferay-portal/commit/6d4c1130eb96bce29fe25911b6d1d65f4e28582d">6d4c1130eb96bce29fe25911b6d1d65f4e28582d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/361/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">here</a>.</h5></details></html>

2021-09-28 20:43 UTC, carolmariaabb commented
ci:test:relevant

2021-09-28 20:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/455/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/455/jenkins-report.html">here</a>.</b></p>

2021-09-28 21:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/361/">test-portal-source-format#361</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/361/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1564894864">[master] ci:test:sf - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-28[13:41:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1114/">publish-testray-report#1114</a><br/></div></div>

2021-09-28 21:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/07358e14977aacb4ffc6ffab0a3cfb42032d0002">07358e14977aacb4ffc6ffab0a3cfb42032d0002</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e401b908c9c127ce6e4d7cc992027277d24eff5">1e401b908c9c127ce6e4d7cc992027277d24eff5</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2361">Acceptance Upstream DXP (master) #2361</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/455/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/455/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/455/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava FAILED
     [exec] &gt; Task :apps:dynamic-data-mapping:dynamic-data-mapping-validator:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:mobile-device-rules:mobile-device-rules-api:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-service:jar
     [exec] warning: Unable to determine whether the annotation org.osgi.annotation.versioning.ProviderType applied to type com.liferay.portal.instance.lifecycle.BasePortalInstanceLifecycleListener is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-service:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-taglib:packageRunBuild
     [exec] Successfully compiled 19 files with Babel.
     [exec] Bundling took 5s
     [exec] BUILD SASS: No scss files found.
     [exec] Minification summary:
     [exec]   Files processed:   147
     [exec]   Files with errors: 10
     [exec]   Before size:       977101
     [exec]   After size:        413198
     [exec]   Delta:             563903
     [exec]   Elapsed:           2.98
     [exec] Received 0
     [exec] Done in 18.30s.
     [exec] 
     [exec] &gt; Task :apps:change-tracking:change-tracking-web:packageRunBuild
     [exec] Bundling took 34s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/ChangeTrackingIndicator.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   2439
     [exec]   Files with errors: 1234
     [exec]   Before size:       7698901
     [exec]   After size:        4757491
     [exec]   Delta:             2941410
     [exec]   Elapsed:           9.38
     [exec] Received 0
     [exec] Done in 46.13s.
     [exec] Gradle build finished at 2021-09-28 21:09:30.994.
     [exec] 1328 actionable tasks: 1266 executed, 62 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-09-28 21:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/455/">test-portal-acceptance-pullrequest(master)#455</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/455/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1564901143">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-28[13:53:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1186/">publish-testray-report#1186</a><br/></div></div>

2021-09-29 10:53 UTC, carolmariaabb commented
ci:test:relevant

2021-09-29 10:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/463/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/463/jenkins-report.html">here</a>.</b></p>

2021-09-29 11:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9">596776d659b936539c7dfed23e61b35bc51a8bb9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9">596776d659b936539c7dfed23e61b35bc51a8bb9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2364">Acceptance Upstream DXP (master) #2364</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/463/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/463/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/463/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-tax-engine-fixed-api:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-cart-taglib:packageRunBuild
     [exec] Using pre-existing NODE_ENV: "test"
     [exec] Successfully compiled 0 files with Babel.
     [exec] Bundling took 107ms
     [exec] BUILD SASS: No scss files found.
     [exec] Minification summary:
     [exec]   Files processed:   0
     [exec]   Files with errors: 0
     [exec]   Before size:       0
     [exec]   After size:        0
     [exec]   Delta:             0
     [exec]   Elapsed:           0.00
     [exec] Received 0
     [exec] Done in 2.90s.
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-service:compileJava
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 93 ms
     [echo] Rsyncing Jenkins report.
[beanshell] Remote execution starting with 1 threads.
[beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 test-1-28 'mkdir -p /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/463/'
[beanshell] Average thread duration: 222ms
[beanshell] Busy slaves:0
[beanshell] Finished slaves:1
[beanshell] Target slaves:1
[beanshell] Total duration: 222
[beanshell] Remote execution completed in 222ms.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210929040730749
     [exec] 
     [exec] &gt; Task :apps:change-tracking:change-tracking-web:packageRunBuild
     [exec] Bundling took 26s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/ChangeTrackingIndicator.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   2439
     [exec]   Files with errors: 1234
     [exec]   Before size:       7698901
     [exec]   After size:        4757491
     [exec]   Delta:             2941410
     [exec]   Elapsed:           8.80
     [exec] Received 0
     [exec] Done in 41.14s.
     [exec] Gradle build finished at 2021-09-29 11:07:49.933.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-09-29 11:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/463/">test-portal-acceptance-pullrequest(master)#463</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/463/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565056200">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-29[03:53:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1200/">publish-testray-report#1200</a><br/></div></div>

2021-09-29 13:19 UTC, carolmariaabb commented
ci:test:relevant

2021-09-29 13:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/411/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/411/jenkins-report.html">here</a>.</b></p>

2021-09-29 13:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9">596776d659b936539c7dfed23e61b35bc51a8bb9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9">596776d659b936539c7dfed23e61b35bc51a8bb9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2364">Acceptance Upstream DXP (master) #2364</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/411/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/411/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/411/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-tax-engine-fixed-api:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-cart-taglib:packageRunBuild
     [exec] Using pre-existing NODE_ENV: "test"
     [exec] Successfully compiled 0 files with Babel.
     [exec] Bundling took 130ms
     [exec] BUILD SASS: No scss files found.
     [exec] Minification summary:
     [exec]   Files processed:   0
     [exec]   Files with errors: 0
     [exec]   Before size:       0
     [exec]   After size:        0
     [exec]   Delta:             0
     [exec]   Elapsed:           0.00
     [exec] Received 0
     [exec] Done in 2.83s.
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-service:compileJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :apps:change-tracking:change-tracking-web:packageRunBuild
     [exec] Bundling took 26s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/ChangeTrackingIndicator.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   2439
     [exec]   Files with errors: 1234
     [exec]   Before size:       7698901
     [exec]   After size:        4757491
     [exec]   Delta:             2941410
     [exec]   Elapsed:           9.02
     [exec] Received 0
     [exec] Done in 41.08s.
     [exec] Gradle build finished at 2021-09-29 13:33:15.074.
     [exec] 1332 actionable tasks: 1270 executed, 62 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-09-29 13:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/411/">test-portal-acceptance-pullrequest(master)#411</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/411/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565077742">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-29[06:19:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1151/">publish-testray-report#1151</a><br/></div></div>

2021-09-29 14:22 UTC, carolmariaabb commented
> ### ❌ ci:test:relevant - 0 out of 1 jobs passed in 14 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [596776d659b936539c7dfed23e61b35bc51a8bb9](https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9)
> 
> #### Upstream Comparison:
> Branch GIT ID: [596776d659b936539c7dfed23e61b35bc51a8bb9](https://github.com/liferay/liferay-portal/commit/596776d659b936539c7dfed23e61b35bc51a8bb9)Jenkins Build URL: [Acceptance Upstream DXP (master) #2364](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2364)
> 
> **ci:test:relevant - 0 out of 1 jobs PASSED**
> ##### For more details click [here](https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/411/jenkins-report.html).
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest(master)](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/411/)###### Job Results:0 Jobs Passed.1 Job Failed.```
>         [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava FAILED
>         [exec] 
>         [exec] > Task :apps:commerce:commerce-tax-engine-fixed-api:autoUpdateXml SKIPPED
>         [exec] 
>         [exec] > Task :apps:commerce:commerce-cart-taglib:packageRunBuild
>         [exec] Using pre-existing NODE_ENV: "test"
>         [exec] Successfully compiled 0 files with Babel.
>         [exec] Bundling took 130ms
>         [exec] BUILD SASS: No scss files found.
>         [exec] Minification summary:
>         [exec]   Files processed:   0
>         [exec]   Files with errors: 0
>         [exec]   Before size:       0
>         [exec]   After size:        0
>         [exec]   Delta:             0
>         [exec]   Elapsed:           0.00
>         [exec] Received 0
>         [exec] Done in 2.83s.
>         [exec] 
>         [exec] > Task :apps:commerce:commerce-service:compileJava
>         [exec] Note: Some input files use or override a deprecated API.
>         [exec] Note: Recompile with -Xlint:deprecation for details.
>         [exec] Note: Some input files use unchecked or unsafe operations.
>         [exec] Note: Recompile with -Xlint:unchecked for details.
>         [exec] 
>         [exec] > Task :apps:change-tracking:change-tracking-web:packageRunBuild
>         [exec] Bundling took 26s
>         [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/ChangeTrackingIndicator.css
>         [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/publications/css/main.css
>         [exec] Minification summary:
>         [exec]   Files processed:   2439
>         [exec]   Files with errors: 1234
>         [exec]   Before size:       7698901
>         [exec]   After size:        4757491
>         [exec]   Delta:             2941410
>         [exec]   Elapsed:           9.02
>         [exec] Received 0
>         [exec] Done in 41.08s.
>         [exec] Gradle build finished at 2021-09-29 13:33:15.074.
>         [exec] 1332 actionable tasks: 1270 executed, 62 up-to-date
>         [exec] 
>         [exec] 
>         [exec] FAILURE: Build failed with an exception.
>         [exec] 
>         [exec] * What went wrong:
>         [exec] Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava'.
>         [exec] > Compilation failed; see the compiler error output for details.
>         [exec] 
>         [exec] * Try:
>         [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>         [exec] 
>         [exec] * Exception is:
>    ```
> 
> #### For upstream results, click [here](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

@antonio91dev Can you please check the CI failures? It seems to be related to your changes.

```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-service:compileJava'.
     [exec] > Compilation failed; see the compiler error output for details.
```

2021-09-30 15:35 UTC, carolmariaabb commented
ci:test:sf

2021-09-30 15:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/617/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">here</a>.</b></p>

2021-09-30 15:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6db2c45f06e4bf3a1982a1eb34467143ad490c37">6db2c45f06e4bf3a1982a1eb34467143ad490c37</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/antonio91dev/liferay-portal/tree/LPS-139879">LPS-139879</a><br/>Branch GIT ID: <a href="https://github.com/antonio91dev/liferay-portal/commit/5a3a048ea794e8332439191cb5e85628b00c6cbc">5a3a048ea794e8332439191cb5e85628b00c6cbc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/617/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">here</a>.</h5></details></html>

2021-09-30 15:45 UTC, liferay-forms commented
ci:test:relevant

2021-09-30 15:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/617/">test-portal-source-format#617</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/617/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565357744">[master] ci:test:sf - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-30[08:37:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/2065/">publish-testray-report#2065</a><br/></div></div>

2021-09-30 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6360/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6360/jenkins-report.html">here</a>.</b></p>

2021-10-01 00:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 10 out of 11 jobs passed</h3><h3>:x: ci:test:relevant - 25 out of 28 jobs passed in 6 hours 33 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2371">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1137401_6360</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6db2c45f06e4bf3a1982a1eb34467143ad490c37">6db2c45f06e4bf3a1982a1eb34467143ad490c37</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fda430587b0211e362c69c5b387d9db14490ca89">fda430587b0211e362c69c5b387d9db14490ca89</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2370">Acceptance Upstream DXP (master) #2370</a></p><details><summary><strong>ci:test:stable - 10 out of 11 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6504/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9023/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7242/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7243/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443548/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333790/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/479950/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482720/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7061/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7060/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333791/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 25 out of 28 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6360/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6505/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6504/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470069/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/479951/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9025/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9023/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7063/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7249/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470070/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/345276/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9328/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7242/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7243/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/481032/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9329/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443548/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333790/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7062/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7248/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/479950/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(ma [...]

2021-10-01 00:12 UTC, liferay-forms commented
Hey @antonio91dev, can you please check if these failures are related to your changes? Thanks

2021-10-01 00:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6360/">test-portal-acceptance-pullrequest(master)#6360</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6360/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565458658">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-09-30[10:37:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/2051/">publish-testray-report#2051</a><br/></div></div>

2021-10-01 11:11 UTC, carolmariaabb commented
ci:reevaluate:1137401_6360

2021-10-01 11:11 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1137401_6360` against the latest valid upstream results.

2021-10-01 11:56 UTC, carolmariaabb commented
ci:reevaluate:1137401_6360

2021-10-01 11:56 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1137401_6360` against the latest valid upstream results.

2021-10-01 12:58 UTC, carolmariaabb commented
ci:test:relevant

2021-10-01 13:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/8540/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8540/jenkins-report.html">here</a>.</b></p>

2021-10-01 14:59 UTC, antonio91dev commented
Hi
@liferay-forms  no , these are not errors related to my changes

2021-10-01 16:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 11 out of 11 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 28 jobs passed in 3 hours 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6d3b62911ed205fcdda9e734338d5e4b4f50e4f3">6d3b62911ed205fcdda9e734338d5e4b4f50e4f3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6d3b62911ed205fcdda9e734338d5e4b4f50e4f3">6d3b62911ed205fcdda9e734338d5e4b4f50e4f3</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2374">Acceptance Upstream DXP (master) #2374</a></p><details><summary><strong>ci:test:stable - 11 out of 11 jobs PASSED</strong></summary><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9493/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8939/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17840/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/479987/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6773/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9497/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7399/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9498/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449421/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9494/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8938/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/8540/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449423/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7433/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6774/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3235/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9496/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7398/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9499/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9493/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470119/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366024/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8939/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17840/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7397/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9500/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/479987/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6773/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8937/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9495/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9497/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470118/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7399/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9498/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449421/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</ [...]

2021-10-01 16:07 UTC, liferay-forms commented
Hey @antonio91dev, can you please check if these failures are related to your changes? Thanks

2021-10-01 16:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/8540/">test-portal-acceptance-pullrequest(master)#8540</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8540/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1565806396">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-10-01[06:00:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/2189/">publish-testray-report#2189</a><br/></div></div>

2021-10-04 11:07 UTC, carolmariaabb commented
ci:test:relevant

2021-10-04 11:07 UTC, carolmariaabb approved these changes

2021-10-04 11:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/387/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/387/jenkins-report.html">here</a>.</b></p>

2021-10-04 13:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 11 out of 11 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 28 jobs passed in 2 hours 13 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2389">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_387</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa9228b4795e4290997695897a0ee8b3704c5c37">fa9228b4795e4290997695897a0ee8b3704c5c37</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a1dc492de3abf5c1d43ce7102dac3d36bd4c8bdb">a1dc492de3abf5c1d43ce7102dac3d36bd4c8bdb</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2387">Acceptance Upstream DXP (master) #2387</a></p><details><summary><strong>ci:test:stable - 11 out of 11 jobs PASSED</strong></summary><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9210/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7667/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480041/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9211/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7416/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443677/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480042/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443678/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9757/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9756/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7666/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 28 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/387/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443679/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/395041/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7417/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442984/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7663/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/422653/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480040/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9210/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9760/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9759/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7667/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480041/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7668/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/422652/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9211/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7416/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7665/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9758/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443677/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7415/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequ [...]

2021-10-04 13:21 UTC, liferay-forms commented
Hey @antonio91dev, can you please check if these failures are related to your changes? Thanks

2021-10-04 18:22 UTC, carolmariaabb commented
ci:reevaluate:1297401_387

2021-10-04 18:22 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1297401_387` against the latest valid upstream results.

2021-10-04 20:22 UTC, carolmariaabb commented
ci:test:relevant

2021-10-04 20:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/492/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/492/jenkins-report.html">here</a>.</b></p>

2021-10-04 20:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/638cf086b3f4e85fcaf3e304731cdbce2ad592d9">638cf086b3f4e85fcaf3e304731cdbce2ad592d9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a60d4300afcf1eee4a14ba5467adac756386dd36">a60d4300afcf1eee4a14ba5467adac756386dd36</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2390">Acceptance Upstream DXP (master) #2390</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/492/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/492/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/492/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>SHA 1a73112a4c06389b54e011e170c249cc2ce29316 was not found in branch 'master-private' on git@github.com:liferay/liferay-portal-ee.git</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-10-04 20:26 UTC, liferay-forms commented
Hey @antonio91dev, can you please check if these failures are related to your changes? Thanks

2021-10-04 20:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/492/">test-portal-acceptance-pullrequest(master)#492</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/492/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1566332832">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-10-04[13:23:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1383/">publish-testray-report#1383</a><br/></div></div>

2021-10-05 10:11 UTC, carolmariaabb commented
ci:test:relevant

2021-10-05 10:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/509/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/509/jenkins-report.html">here</a>.</b></p>

2021-10-05 12:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 11 out of 11 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 27 out of 28 jobs passed in 1 hour 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/59bcc8518e827673421d4d4944d9706421d06c70">59bcc8518e827673421d4d4944d9706421d06c70</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/59bcc8518e827673421d4d4944d9706421d06c70">59bcc8518e827673421d4d4944d9706421d06c70</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2395">Acceptance Upstream DXP (master) #2395</a></p><details><summary><strong>ci:test:stable - 11 out of 11 jobs PASSED</strong></summary><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7300/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7997/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7998/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7303/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9985/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9987/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7999/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7995/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9983/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7301/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/336663/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 26 out of 28 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/509/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480102/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9445/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476951/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7996/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7300/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/336664/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/395102/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9989/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9447/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9446/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7997/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7998/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7264/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7263/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7303/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9985/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9988/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9984/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9987/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7302/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7999/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7995/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9983/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-ba [...]

2021-10-05 12:13 UTC, carolmariaabb commented
ci:forward

2021-10-05 12:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-10-05 12:14 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-10-05 12:14 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/75//consoleFull)

2021-10-05 12:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/108203
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/75//consoleFull)

2021-10-05 12:15 UTC, closed without merging

2021-10-05 12:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/509/">test-portal-acceptance-pullrequest(master)#509</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/509/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-forms/liferay-portal/pull/972">liferay-forms#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1566545310">[master] ci:test:relevant - antonio91dev &gt; liferay-forms - PR#972 - 2021-10-05[03:11:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1418/">publish-testray-report#1418</a><br/></div></div>